export enum BIRTH_DATE_NUMBER_VNM_SUBSECTION {
    ONE = 'MỘT',
    TWO = 'HAI',
    THREE = 'BA',
    FOUR = 'BỐN',
    FIVE = 'NĂM HOẶC NHIỀU HƠN',
    ZERO = 'KHÔNG CÓ'
}

export enum BIRTH_DATE_NUMBER_SUBSECTION {
    ONE = ' số 1',
    TWO = ' số 2',
    THREE = ' số 3',
    FOUR = ' số 4',
    FIVE = ' số 5',
    SIX = ' số 6',
    SEVEN = ' số 7',
    EIGHT = ' số 8',
    NINE = ' số 9',
    ZERO = ' số 0'
}

type TBirthDateNumberMeaning = {
    [key: number]: {
        [key: number]: {
            title: string
            meaning: string
        }
    }
}

export const BIRTH_DATE_NUMBER_MEANING: TBirthDateNumberMeaning = {
    1: {
        1: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.ONE + BIRTH_DATE_NUMBER_SUBSECTION.ONE,
            meaning: 'Những người có Biểu đồ ngày sinh có một số 1 thường gặp một chút khó khăn trong việc thể hiện bản thân qua ngôn ngữ. Điều này không có nghĩa là họ không thể nói chuyện một cách suôn sẻ, mà là họ khó diễn đạt được cảm xúc nội tâm của mình.\n' + '\n' + 'Họ có thể nói rất lưu loát và đầy thuyết phục về các đề tài không liên quan đến diễn đạt cảm xúc cá nhân, nhưng thường không biết cách biểu đạt bản thân hoặc diễn tả những gì mình đang cảm thấy. Chỉ khi nào họ học được cách làm chủ bản thân - kết quả của quá trình trưởng thành và thấu hiểu - thì điều này mới được cải thiện. Đôi khi họ sẽ cố ý nói ra những lời hoàn toàn trái ngược với suy nghĩ thật sự của mình như một kiểu phản ứng tự vệ - tức là họ Cố ý làm tổn thương hoặc xúc phạm người khác để tự bảo vệ bản thân mình. Điều này khiến vấn đề ban đầu trở nên nghiêm trọng hơn và gây ra những cuộc tranh cãi gay gắt. Họ cần tập suy nghĩ cẩn trọng trước khi phát biểu, và họ có thể làm được điều ấy bằng cách học kiểm soát phản ứng của bản thân trước các ý kiến, lời phê bình, vì những lời nói đã nói ra thì không thể thu hồi và cảm giác tổn thương rất khó được chữa lành. Để cải thiện hạn chế này, hãy lấy một quyển số trắng và ghi ngày tháng hiện tại. Sau đó, vào buổi tối, trước khi đi ngủ, hãy dành vài phút viết ra những suy nghĩ và cảm nhận của bạn về ngày hôm nay. Nhớ ghi rõ cả những việc bạn vốn dĩ muốn làm, những lời bạn vốn dĩ muốn nói, nhưng rốt cuộc đã không thực hiện được và những điều bạn đã nói hay lỡ làm mà bạn ước gì bạn đã không làm hay nói. Buổi sáng hôm sau, bạn hãy đọc to toàn bộ nội dung đó trước một tấm gương lớn và quan sát ngôn ngữ cơ thể bạn.\n' +
                '\n' + 'Hãy làm điều này thường xuyên và bạn sẽ nhìn thấy sự tự tin trong việc diễn đạt bản thân được cải thiện thấy rõ, về cuộc sống, những người có một số 1 thường cảm thấy thiếu một điều gì đó trong cuộc sống, mặc dù thoạt nhìn họ rất đủ đầy ở một số mặt.',

        },
        2: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.TWO + BIRTH_DATE_NUMBER_SUBSECTION.ONE,
            meaning: 'Người có hai số 1 (11) trong Biểu đồ ngày sinh là người may mắn nhất trong cả nhóm, bởi sự cân bằng trời cho trong việc diễn đạt nội tâm. Đây là một đặc điểm nên được sử dụng một cách khôn ngoan - không bao giờ lạm dụng nó cho mục đích thao túng người khác. (Đồng thời hãy nhớ đừng mất kiên nhẫn với những người không may mắn không có hai số 1 giống bạn, đặc biệt nếu đó là người yêu hoặc người bạn đời của bạn.) Người có hai số 1 thường có khả năng nhìn nhận các vấn đề hay các cuộc tranh luận theo cả hai mặt, và vì vậy họ hoàn toàn có khả năng chuyển sang hướng đối lập trong một cuộc thảo luận nếu quan điểm của bên đó có vẻ có giá trị hơn. Điều này giúp họ không bị sa vào tư duy bảo thủ, thứ khiến tầm hiểu biết bị giới hạn một chiều, và vì thế bản thân họ cũng thường ít khi bắt bẻ những “ lỗi sai ” của người khác. Có thể nói người có hai số 1 trong biểu đồ thường dễ có cuộc sống cân bằng, an vui, bất kể cuộc sống có diễn ra thế nào. Về nhận định này, tôi có hai điều muốn chia sẻ kỹ hơn : Một Biểu đồ ngày sinh sẽ bao gồm rất nhiều yếu tố chi tiết bên trong, yếu tố này hòa quyện với yếu tố kia, hay yếu tố này mâu thuẫn với yếu tố kia, làm giảm giá trị của yếu tố kia.\n' +
                '\n' + 'Ví dụ, nếu một người có được hai số 1 nhưng lại trống hoàn toàn cột giữa (4-5-6 - mang ý nghĩa Mũi tên uất giận, vì họ mãi không đạt được điều mình khát khao muốn có) , và đặc biệt nếu có thêm số 7 (hay 77, hay 777) thì người đó rất dễ gặp phải một trong những điều bất ý lớn trong các khía cạnh: sức khỏe, tiền tài, tình yêu, sự nghiệp ... Nhưng nhờ sức mạnh của hai số 1, người đó vẫn hay dùng lòng tin để tiếp thu cái mới, từ đó khiến bản thân gặp nhiều thiệt thòi. Tuy nhiên, nhờ trong Biểu đồ ngày sinh của tôi có hai số 1 (11) nên tôi có được một đặc điểm (như đã đề cập ở trên) : dễ dàng nhìn được hai mặt của một vấn đề, chịu thay đổi quan điểm một khi thấy các quan điểm khác cũng đúng hoặc có giá trị. Điều này đặc biệt ý nghĩa với các vấn đề mang tính trực giác, đòi hỏi sự hiểu biết sâu xa hơn những gì mắt thường nhìn thấy. Cho nên hiện giờ tôi đã thôi không còn dùng khái niệm “ thấy mới tin ” nữa, mà bắt đầu lắng tâm mình hơn, mỗi ngày một phát huy trực giác (còn gọi là “ con mắt ” bên trong) để cảm mọi việc, nhờ vậy tôi có thể tiếp thu nhiều cái mới mẻ hơn, rộng lớn hơn. Như vậy, hai số 1 (11) đã giúp tôi hóa giải bớt tính “ cứng đầu ” của Mũi tên 1-4-7 đó.\n' +
                '\n' + 'Trở lại với những đặc điểm nổi bật của hai số 1 (11) :\n' + '\n' + 'Chính nhờ những yếu tố tích cực, dung hòa và cân bằng này mà người có hai số 1 trong biểu đồ dễ trở thành các chính trị gia thành công hoặc người của công chúng, người nổi tiếng. Yếu tố hai số 1 làm nổi bật nhận thức về con người, cũng như cách biểu đạt bản thân và khả năng nhìn nhận vấn đề một cách đa chiều, không phiến diện, giúp giảm thiểu khả năng bị hiểu lầm.',
        },
        3: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.THREE + BIRTH_DATE_NUMBER_SUBSECTION.ONE,
            meaning: 'Với những người có ba số 1 trong Biểu đồ ngày sinh, có hai khả năng khá đối lập xảy ra trong thực tế. Khả năng thường gặp nhất là những người này thuộc dạng nói rất nhiều, thường có mặt trong rất nhiều cuộc trò chuyện sôi nổi mà trong đó họ trở nên nổi bật và thú vị. Nhìn chung họ thấy cuộc sống dễ chịu và thường cố gắng chia sẻ điều đó với những người xung quanh, Nhóm thứ hai là những người cũng có ba số 1 nhưng lại không có số nào ở Trục ngang Tinh thần (tức là không có các số 2-5-8) . Những người này khá im lặng, hướng nội, bẽn lẽn, đặc biệt là với người lạ. Tuy nhiên, họ có thể hoạt bát và nói nhiều khi trò chuyện với bạn bè thân thiết hoặc người thân trong nhà - đó là những lúc họ cảm thấy thoải mái. Những người này thường dễ diễn đạt cảm xúc hay nội tâm của mình bằng cách viết, vì khi đó dòng suy nghĩ của họ liền mạch hơn, không bị cản trở bởi sự nhạy cảm quá mức của họ. Nếu bạn thuộc nhóm này mà chưa biết sức mạnh khả năng viết lách của mình, hãy thử xem sao. Hãy xem viết lách là một cách để tập diễn đạt bản thân cho trôi chảy, khơi thông những cảm xúc rối rắm tắc nghẽn trong lòng, cũng như là một cách để tự chữa lành. Ngoài ra, còn một khả năng nữa ở những người có ba số 1 mà bản thân tôi quan sát thấy, đó là tâm trạng lúc vui lúc buồn. Tùy theo những yếu tố khác trong Biểu đồ ngày sinh mà tỷ lệ vui buồn sẽ gia giảm khác nhau, tốt nhất thì được 5/5, còn không thì 4/6, không nữa thì 3/7, lúc vui họ có xu hướng nói rất nhiều, lúc buồn thì ngồi im, không quan tâm tới ai.',
        },
        4: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.FOUR + BIRTH_DATE_NUMBER_SUBSECTION.ONE,
            meaning: 'Người có bốn số 1 trong ngày sinh thường gặp trục trặc với vấn đề diễn đạt bằng lời, và vì vậy, rất dễ bị người khác hiểu lầm. Nhưng cuộc sống nhanh chóng dạy họ giấu đi những cảm xúc rối rắm bằng một nụ cười, cho dù họ có khuynh hướng dẫn tiếp tục chịu đựng bên trong cho đến khi tự có ý thức giải tỏa những cảm xúc đó và sống lẹ làng hơn. Nói một cách dễ hiểu, những người có bốn số 1 thường tự làm mình khổ tâm. Số 1 mang đặc tính về “ cái tôi ” của mỗi người, vậy nên hãy tưởng tượng một người có đến bốn lần “ cái tôi ” như vậy sẽ như thế nào. Họ có “ cái tôi rất mạnh, nhưng rất khó diễn đạt những cảm giác sâu đậm như vậy về bản thân mình. Vì vậy, Thầy David khuyên: vì hạnh phúc của chính mình và của những người thân, những người có bốn số 1 phải học cách kiểm soát cảm xúc của mình. Khi họ thả lỏng hơn, bớt căng thẳng, bớt thiếu tự tin (đôi khi họ không nhận ra điều này, mà trái lại, họ có thể cảm thấy mình quá tự tin là đằng khác), họ sẽ cảm thấy ít bị cản trở hơn và diễn đạt cảm xúc của mình một cách thoải mái hơn, thay vì cứ đè nén những sầu muộn, rối rắm trong nội tâm của mình.',
        },
        5: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.FIVE + BIRTH_DATE_NUMBER_SUBSECTION.ONE,
            meaning: 'Với năm hay sáu số 1 trên Biểu đồ ngày sinh, “ cái tôi ” thường bị đè nén để giảm bớt các khó khăn trong việc diễn đạt cảm xúc cá nhân. Những người trẻ tuổi thuộc nhóm này thường cảm thấy buồn vì bị mọi người xung quanh hiểu lầm. Điều này dẫn đến sự tách rời, từ đó gây gia sự cô độc. Họ có thể phát triển theo hướng bị ám ảnh với ngoại hình và hành động của mình, cũng như thường gắn rất nhiều gương trong nhà nhưng lại có xu hướng giấu chúng đi để tránh người khác nghĩ họ quá tự tôn. Nhưng họ vẫn bí mật ngắm mình trong gương mỗi khi có dịp. Tính vị kỷ và “ tự lừa mình ” này có thể gây ra sự mất cân bằng về tâm thần, chúng ta có thể giúp trẻ thuộc nhóm có quá nhiều số 1 gia tăng nhận thức bằng cách cho chúng tham gia nhiều hoạt động nghệ thuật khác nhau, như viết lách, làm thơ, vẽ, làm đồ gốm,... Điều này có thể áp dụng được cho trẻ mọi lứa tuổi.'
        }
    },
    2: {
        1: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.ONE + BIRTH_DATE_NUMBER_SUBSECTION.TWO,
            meaning: 'Những người có Biểu đồ ngày sinh có một số 1 thường gặp một chút khó khăn trong việc thể hiện bản thân qua ngôn ngữ. Điều này không có nghĩa là họ không thể nói chuyện một cách suôn sẻ, mà là họ khó diễn đạt được cảm xúc nội tâm của mình.\n' + '\n' + 'Họ có thể nói rất lưu loát và đầy thuyết phục về các đề tài không liên quan đến diễn đạt cảm xúc cá nhân, nhưng thường không biết cách biểu đạt bản thân hoặc diễn tả những gì mình đang cảm thấy. Chỉ khi nào họ học được cách làm chủ bản thân - kết quả của quá trình trưởng thành và thấu hiểu - thì điều này mới được cải thiện. Đôi khi họ sẽ cố ý nói ra những lời hoàn toàn trái ngược với suy nghĩ thật sự của mình như một kiểu phản ứng tự vệ - tức là họ Cố ý làm tổn thương hoặc xúc phạm người khác để tự bảo vệ bản thân mình. Điều này khiến vấn đề ban đầu trở nên nghiêm trọng hơn và gây ra những cuộc tranh cãi gay gắt. Họ cần tập suy nghĩ cẩn trọng trước khi phát biểu, và họ có thể làm được điều ấy bằng cách học kiểm soát phản ứng của bản thân trước các ý kiến, lời phê bình, vì những lời nói đã nói ra thì không thể thu hồi và cảm giác tổn thương rất khó được chữa lành. Để cải thiện hạn chế này, hãy lấy một quyển số trắng và ghi ngày tháng hiện tại. Sau đó, vào buổi tối, trước khi đi ngủ, hãy dành vài phút viết ra những suy nghĩ và cảm nhận của bạn về ngày hôm nay. Nhớ ghi rõ cả những việc bạn vốn dĩ muốn làm, những lời bạn vốn dĩ muốn nói, nhưng rốt cuộc đã không thực hiện được và những điều bạn đã nói hay lỡ làm mà bạn ước gì bạn đã không làm hay nói. Buổi sáng hôm sau, bạn hãy đọc to toàn bộ nội dung đó trước một tấm gương lớn và quan sát ngôn ngữ cơ thể bạn.\n' +
                '\n' + 'Hãy làm điều này thường xuyên và bạn sẽ nhìn thấy sự tự tin trong việc diễn đạt bản thân được cải thiện thấy rõ, về cuộc sống, những người có một số 1 thường cảm thấy thiếu một điều gì đó trong cuộc sống, mặc dù thoạt nhìn họ rất đủ đầy ở một số mặt.',
        },
        2: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.TWO + BIRTH_DATE_NUMBER_SUBSECTION.TWO,
            meaning: 'Người có hai số 1 (11) trong Biểu đồ ngày sinh là người may mắn nhất trong cả nhóm, bởi sự cân bằng trời cho trong việc diễn đạt nội tâm. Đây là một đặc điểm nên được sử dụng một cách khôn ngoan - không bao giờ lạm dụng nó cho mục đích thao túng người khác. (Đồng thời hãy nhớ đừng mất kiên nhẫn với những người không may mắn không có hai số 1 giống bạn, đặc biệt nếu đó là người yêu hoặc người bạn đời của bạn.) Người có hai số 1 thường có khả năng nhìn nhận các vấn đề hay các cuộc tranh luận theo cả hai mặt, và vì vậy họ hoàn toàn có khả năng chuyển sang hướng đối lập trong một cuộc thảo luận nếu quan điểm của bên đó có vẻ có giá trị hơn. Điều này giúp họ không bị sa vào tư duy bảo thủ, thứ khiến tầm hiểu biết bị giới hạn một chiều, và vì thế bản thân họ cũng thường ít khi bắt bẻ những “ lỗi sai ” của người khác. Có thể nói người có hai số 1 trong biểu đồ thường dễ có cuộc sống cân bằng, an vui, bất kể cuộc sống có diễn ra thế nào. Về nhận định này, tôi có hai điều muốn chia sẻ kỹ hơn : Một Biểu đồ ngày sinh sẽ bao gồm rất nhiều yếu tố chi tiết bên trong, yếu tố này hòa quyện với yếu tố kia, hay yếu tố này mâu thuẫn với yếu tố kia, làm giảm giá trị của yếu tố kia.\n' +
                '\n' + 'Ví dụ, nếu một người có được hai số 1 nhưng lại trống hoàn toàn cột giữa (4-5-6 - mang ý nghĩa Mũi tên uất giận, vì họ mãi không đạt được điều mình khát khao muốn có) , và đặc biệt nếu có thêm số 7 (hay 77, hay 777) thì người đó rất dễ gặp phải một trong những điều bất ý lớn trong các khía cạnh: sức khỏe, tiền tài, tình yêu, sự nghiệp ... Nhưng nhờ sức mạnh của hai số 1, người đó vẫn hay dùng lòng tin để tiếp thu cái mới, từ đó khiến bản thân gặp nhiều thiệt thòi. Tuy nhiên, nhờ trong Biểu đồ ngày sinh của tôi có hai số 1 (11) nên tôi có được một đặc điểm (như đã đề cập ở trên) : dễ dàng nhìn được hai mặt của một vấn đề, chịu thay đổi quan điểm một khi thấy các quan điểm khác cũng đúng hoặc có giá trị. Điều này đặc biệt ý nghĩa với các vấn đề mang tính trực giác, đòi hỏi sự hiểu biết sâu xa hơn những gì mắt thường nhìn thấy. Cho nên hiện giờ tôi đã thôi không còn dùng khái niệm “ thấy mới tin ” nữa, mà bắt đầu lắng tâm mình hơn, mỗi ngày một phát huy trực giác (còn gọi là “ con mắt ” bên trong) để cảm mọi việc, nhờ vậy tôi có thể tiếp thu nhiều cái mới mẻ hơn, rộng lớn hơn. Như vậy, hai số 1 (11) đã giúp tôi hóa giải bớt tính “ cứng đầu ” của Mũi tên 1-4-7 đó.\n' +
                '\n' + 'Trở lại với những đặc điểm nổi bật của hai số 1 (11) :\n' + '\n' + 'Chính nhờ những yếu tố tích cực, dung hòa và cân bằng này mà người có hai số 1 trong biểu đồ dễ trở thành các chính trị gia thành công hoặc người của công chúng, người nổi tiếng. Yếu tố hai số 1 làm nổi bật nhận thức về con người, cũng như cách biểu đạt bản thân và khả năng nhìn nhận vấn đề một cách đa chiều, không phiến diện, giúp giảm thiểu khả năng bị hiểu lầm.',
        },
        3: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.THREE + BIRTH_DATE_NUMBER_SUBSECTION.TWO,
            meaning: 'Với những người có ba số 1 trong Biểu đồ ngày sinh, có hai khả năng khá đối lập xảy ra trong thực tế. Khả năng thường gặp nhất là những người này thuộc dạng nói rất nhiều, thường có mặt trong rất nhiều cuộc trò chuyện sôi nổi mà trong đó họ trở nên nổi bật và thú vị. Nhìn chung họ thấy cuộc sống dễ chịu và thường cố gắng chia sẻ điều đó với những người xung quanh, Nhóm thứ hai là những người cũng có ba số 1 nhưng lại không có số nào ở Trục ngang Tinh thần (tức là không có các số 2-5-8) . Những người này khá im lặng, hướng nội, bẽn lẽn, đặc biệt là với người lạ. Tuy nhiên, họ có thể hoạt bát và nói nhiều khi trò chuyện với bạn bè thân thiết hoặc người thân trong nhà - đó là những lúc họ cảm thấy thoải mái. Những người này thường dễ diễn đạt cảm xúc hay nội tâm của mình bằng cách viết, vì khi đó dòng suy nghĩ của họ liền mạch hơn, không bị cản trở bởi sự nhạy cảm quá mức của họ. Nếu bạn thuộc nhóm này mà chưa biết sức mạnh khả năng viết lách của mình, hãy thử xem sao. Hãy xem viết lách là một cách để tập diễn đạt bản thân cho trôi chảy, khơi thông những cảm xúc rối rắm tắc nghẽn trong lòng, cũng như là một cách để tự chữa lành. Ngoài ra, còn một khả năng nữa ở những người có ba số 1 mà bản thân tôi quan sát thấy, đó là tâm trạng lúc vui lúc buồn. Tùy theo những yếu tố khác trong Biểu đồ ngày sinh mà tỷ lệ vui buồn sẽ gia giảm khác nhau, tốt nhất thì được 5/5, còn không thì 4/6, không nữa thì 3/7, lúc vui họ có xu hướng nói rất nhiều, lúc buồn thì ngồi im, không quan tâm tới ai.',
        },
        4: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.FOUR + BIRTH_DATE_NUMBER_SUBSECTION.TWO,
            meaning: 'Người có bốn số 1 trong ngày sinh thường gặp trục trặc với vấn đề diễn đạt bằng lời, và vì vậy, rất dễ bị người khác hiểu lầm. Nhưng cuộc sống nhanh chóng dạy họ giấu đi những cảm xúc rối rắm bằng một nụ cười, cho dù họ có khuynh hướng dẫn tiếp tục chịu đựng bên trong cho đến khi tự có ý thức giải tỏa những cảm xúc đó và sống lẹ làng hơn. Nói một cách dễ hiểu, những người có bốn số 1 thường tự làm mình khổ tâm. Số 1 mang đặc tính về “ cái tôi ” của mỗi người, vậy nên hãy tưởng tượng một người có đến bốn lần “ cái tôi ” như vậy sẽ như thế nào. Họ có “ cái tôi rất mạnh, nhưng rất khó diễn đạt những cảm giác sâu đậm như vậy về bản thân mình. Vì vậy, Thầy David khuyên: vì hạnh phúc của chính mình và của những người thân, những người có bốn số 1 phải học cách kiểm soát cảm xúc của mình. Khi họ thả lỏng hơn, bớt căng thẳng, bớt thiếu tự tin (đôi khi họ không nhận ra điều này, mà trái lại, họ có thể cảm thấy mình quá tự tin là đằng khác), họ sẽ cảm thấy ít bị cản trở hơn và diễn đạt cảm xúc của mình một cách thoải mái hơn, thay vì cứ đè nén những sầu muộn, rối rắm trong nội tâm của mình.',
        },
        5: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.FIVE + BIRTH_DATE_NUMBER_SUBSECTION.TWO,
            meaning: 'Với năm hay sáu số 1 trên Biểu đồ ngày sinh, “ cái tôi ” thường bị đè nén để giảm bớt các khó khăn trong việc diễn đạt cảm xúc cá nhân. Những người trẻ tuổi thuộc nhóm này thường cảm thấy buồn vì bị mọi người xung quanh hiểu lầm. Điều này dẫn đến sự tách rời, từ đó gây gia sự cô độc. Họ có thể phát triển theo hướng bị ám ảnh với ngoại hình và hành động của mình, cũng như thường gắn rất nhiều gương trong nhà nhưng lại có xu hướng giấu chúng đi để tránh người khác nghĩ họ quá tự tôn. Nhưng họ vẫn bí mật ngắm mình trong gương mỗi khi có dịp. Tính vị kỷ và “ tự lừa mình ” này có thể gây ra sự mất cân bằng về tâm thần, chúng ta có thể giúp trẻ thuộc nhóm có quá nhiều số 1 gia tăng nhận thức bằng cách cho chúng tham gia nhiều hoạt động nghệ thuật khác nhau, như viết lách, làm thơ, vẽ, làm đồ gốm,... Điều này có thể áp dụng được cho trẻ mọi lứa tuổi.'
        }
    },
    3: {
        1: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.ONE + BIRTH_DATE_NUMBER_SUBSECTION.THREE,
            meaning: 'Những người có Biểu đồ ngày sinh có một số 1 thường gặp một chút khó khăn trong việc thể hiện bản thân qua ngôn ngữ. Điều này không có nghĩa là họ không thể nói chuyện một cách suôn sẻ, mà là họ khó diễn đạt được cảm xúc nội tâm của mình.\n' + '\n' + 'Họ có thể nói rất lưu loát và đầy thuyết phục về các đề tài không liên quan đến diễn đạt cảm xúc cá nhân, nhưng thường không biết cách biểu đạt bản thân hoặc diễn tả những gì mình đang cảm thấy. Chỉ khi nào họ học được cách làm chủ bản thân - kết quả của quá trình trưởng thành và thấu hiểu - thì điều này mới được cải thiện. Đôi khi họ sẽ cố ý nói ra những lời hoàn toàn trái ngược với suy nghĩ thật sự của mình như một kiểu phản ứng tự vệ - tức là họ Cố ý làm tổn thương hoặc xúc phạm người khác để tự bảo vệ bản thân mình. Điều này khiến vấn đề ban đầu trở nên nghiêm trọng hơn và gây ra những cuộc tranh cãi gay gắt. Họ cần tập suy nghĩ cẩn trọng trước khi phát biểu, và họ có thể làm được điều ấy bằng cách học kiểm soát phản ứng của bản thân trước các ý kiến, lời phê bình, vì những lời nói đã nói ra thì không thể thu hồi và cảm giác tổn thương rất khó được chữa lành. Để cải thiện hạn chế này, hãy lấy một quyển số trắng và ghi ngày tháng hiện tại. Sau đó, vào buổi tối, trước khi đi ngủ, hãy dành vài phút viết ra những suy nghĩ và cảm nhận của bạn về ngày hôm nay. Nhớ ghi rõ cả những việc bạn vốn dĩ muốn làm, những lời bạn vốn dĩ muốn nói, nhưng rốt cuộc đã không thực hiện được và những điều bạn đã nói hay lỡ làm mà bạn ước gì bạn đã không làm hay nói. Buổi sáng hôm sau, bạn hãy đọc to toàn bộ nội dung đó trước một tấm gương lớn và quan sát ngôn ngữ cơ thể bạn.\n' +
                '\n' + 'Hãy làm điều này thường xuyên và bạn sẽ nhìn thấy sự tự tin trong việc diễn đạt bản thân được cải thiện thấy rõ, về cuộc sống, những người có một số 1 thường cảm thấy thiếu một điều gì đó trong cuộc sống, mặc dù thoạt nhìn họ rất đủ đầy ở một số mặt.',
        },
        2: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.TWO + BIRTH_DATE_NUMBER_SUBSECTION.THREE,
            meaning: 'Người có hai số 1 (11) trong Biểu đồ ngày sinh là người may mắn nhất trong cả nhóm, bởi sự cân bằng trời cho trong việc diễn đạt nội tâm. Đây là một đặc điểm nên được sử dụng một cách khôn ngoan - không bao giờ lạm dụng nó cho mục đích thao túng người khác. (Đồng thời hãy nhớ đừng mất kiên nhẫn với những người không may mắn không có hai số 1 giống bạn, đặc biệt nếu đó là người yêu hoặc người bạn đời của bạn.) Người có hai số 1 thường có khả năng nhìn nhận các vấn đề hay các cuộc tranh luận theo cả hai mặt, và vì vậy họ hoàn toàn có khả năng chuyển sang hướng đối lập trong một cuộc thảo luận nếu quan điểm của bên đó có vẻ có giá trị hơn. Điều này giúp họ không bị sa vào tư duy bảo thủ, thứ khiến tầm hiểu biết bị giới hạn một chiều, và vì thế bản thân họ cũng thường ít khi bắt bẻ những “ lỗi sai ” của người khác. Có thể nói người có hai số 1 trong biểu đồ thường dễ có cuộc sống cân bằng, an vui, bất kể cuộc sống có diễn ra thế nào. Về nhận định này, tôi có hai điều muốn chia sẻ kỹ hơn : Một Biểu đồ ngày sinh sẽ bao gồm rất nhiều yếu tố chi tiết bên trong, yếu tố này hòa quyện với yếu tố kia, hay yếu tố này mâu thuẫn với yếu tố kia, làm giảm giá trị của yếu tố kia.\n' +
                '\n' + 'Ví dụ, nếu một người có được hai số 1 nhưng lại trống hoàn toàn cột giữa (4-5-6 - mang ý nghĩa Mũi tên uất giận, vì họ mãi không đạt được điều mình khát khao muốn có) , và đặc biệt nếu có thêm số 7 (hay 77, hay 777) thì người đó rất dễ gặp phải một trong những điều bất ý lớn trong các khía cạnh: sức khỏe, tiền tài, tình yêu, sự nghiệp ... Nhưng nhờ sức mạnh của hai số 1, người đó vẫn hay dùng lòng tin để tiếp thu cái mới, từ đó khiến bản thân gặp nhiều thiệt thòi. Tuy nhiên, nhờ trong Biểu đồ ngày sinh của tôi có hai số 1 (11) nên tôi có được một đặc điểm (như đã đề cập ở trên) : dễ dàng nhìn được hai mặt của một vấn đề, chịu thay đổi quan điểm một khi thấy các quan điểm khác cũng đúng hoặc có giá trị. Điều này đặc biệt ý nghĩa với các vấn đề mang tính trực giác, đòi hỏi sự hiểu biết sâu xa hơn những gì mắt thường nhìn thấy. Cho nên hiện giờ tôi đã thôi không còn dùng khái niệm “ thấy mới tin ” nữa, mà bắt đầu lắng tâm mình hơn, mỗi ngày một phát huy trực giác (còn gọi là “ con mắt ” bên trong) để cảm mọi việc, nhờ vậy tôi có thể tiếp thu nhiều cái mới mẻ hơn, rộng lớn hơn. Như vậy, hai số 1 (11) đã giúp tôi hóa giải bớt tính “ cứng đầu ” của Mũi tên 1-4-7 đó.\n' +
                '\n' + 'Trở lại với những đặc điểm nổi bật của hai số 1 (11) :\n' + '\n' + 'Chính nhờ những yếu tố tích cực, dung hòa và cân bằng này mà người có hai số 1 trong biểu đồ dễ trở thành các chính trị gia thành công hoặc người của công chúng, người nổi tiếng. Yếu tố hai số 1 làm nổi bật nhận thức về con người, cũng như cách biểu đạt bản thân và khả năng nhìn nhận vấn đề một cách đa chiều, không phiến diện, giúp giảm thiểu khả năng bị hiểu lầm.',
        },
        3: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.THREE + BIRTH_DATE_NUMBER_SUBSECTION.THREE,
            meaning: 'Với những người có ba số 1 trong Biểu đồ ngày sinh, có hai khả năng khá đối lập xảy ra trong thực tế. Khả năng thường gặp nhất là những người này thuộc dạng nói rất nhiều, thường có mặt trong rất nhiều cuộc trò chuyện sôi nổi mà trong đó họ trở nên nổi bật và thú vị. Nhìn chung họ thấy cuộc sống dễ chịu và thường cố gắng chia sẻ điều đó với những người xung quanh, Nhóm thứ hai là những người cũng có ba số 1 nhưng lại không có số nào ở Trục ngang Tinh thần (tức là không có các số 2-5-8) . Những người này khá im lặng, hướng nội, bẽn lẽn, đặc biệt là với người lạ. Tuy nhiên, họ có thể hoạt bát và nói nhiều khi trò chuyện với bạn bè thân thiết hoặc người thân trong nhà - đó là những lúc họ cảm thấy thoải mái. Những người này thường dễ diễn đạt cảm xúc hay nội tâm của mình bằng cách viết, vì khi đó dòng suy nghĩ của họ liền mạch hơn, không bị cản trở bởi sự nhạy cảm quá mức của họ. Nếu bạn thuộc nhóm này mà chưa biết sức mạnh khả năng viết lách của mình, hãy thử xem sao. Hãy xem viết lách là một cách để tập diễn đạt bản thân cho trôi chảy, khơi thông những cảm xúc rối rắm tắc nghẽn trong lòng, cũng như là một cách để tự chữa lành. Ngoài ra, còn một khả năng nữa ở những người có ba số 1 mà bản thân tôi quan sát thấy, đó là tâm trạng lúc vui lúc buồn. Tùy theo những yếu tố khác trong Biểu đồ ngày sinh mà tỷ lệ vui buồn sẽ gia giảm khác nhau, tốt nhất thì được 5/5, còn không thì 4/6, không nữa thì 3/7, lúc vui họ có xu hướng nói rất nhiều, lúc buồn thì ngồi im, không quan tâm tới ai.',
        },
        4: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.FOUR + BIRTH_DATE_NUMBER_SUBSECTION.THREE,
            meaning: 'Người có bốn số 1 trong ngày sinh thường gặp trục trặc với vấn đề diễn đạt bằng lời, và vì vậy, rất dễ bị người khác hiểu lầm. Nhưng cuộc sống nhanh chóng dạy họ giấu đi những cảm xúc rối rắm bằng một nụ cười, cho dù họ có khuynh hướng dẫn tiếp tục chịu đựng bên trong cho đến khi tự có ý thức giải tỏa những cảm xúc đó và sống lẹ làng hơn. Nói một cách dễ hiểu, những người có bốn số 1 thường tự làm mình khổ tâm. Số 1 mang đặc tính về “ cái tôi ” của mỗi người, vậy nên hãy tưởng tượng một người có đến bốn lần “ cái tôi ” như vậy sẽ như thế nào. Họ có “ cái tôi rất mạnh, nhưng rất khó diễn đạt những cảm giác sâu đậm như vậy về bản thân mình. Vì vậy, Thầy David khuyên: vì hạnh phúc của chính mình và của những người thân, những người có bốn số 1 phải học cách kiểm soát cảm xúc của mình. Khi họ thả lỏng hơn, bớt căng thẳng, bớt thiếu tự tin (đôi khi họ không nhận ra điều này, mà trái lại, họ có thể cảm thấy mình quá tự tin là đằng khác), họ sẽ cảm thấy ít bị cản trở hơn và diễn đạt cảm xúc của mình một cách thoải mái hơn, thay vì cứ đè nén những sầu muộn, rối rắm trong nội tâm của mình.',
        },
        5: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.FIVE + BIRTH_DATE_NUMBER_SUBSECTION.THREE,
            meaning: 'Với năm hay sáu số 1 trên Biểu đồ ngày sinh, “ cái tôi ” thường bị đè nén để giảm bớt các khó khăn trong việc diễn đạt cảm xúc cá nhân. Những người trẻ tuổi thuộc nhóm này thường cảm thấy buồn vì bị mọi người xung quanh hiểu lầm. Điều này dẫn đến sự tách rời, từ đó gây gia sự cô độc. Họ có thể phát triển theo hướng bị ám ảnh với ngoại hình và hành động của mình, cũng như thường gắn rất nhiều gương trong nhà nhưng lại có xu hướng giấu chúng đi để tránh người khác nghĩ họ quá tự tôn. Nhưng họ vẫn bí mật ngắm mình trong gương mỗi khi có dịp. Tính vị kỷ và “ tự lừa mình ” này có thể gây ra sự mất cân bằng về tâm thần, chúng ta có thể giúp trẻ thuộc nhóm có quá nhiều số 1 gia tăng nhận thức bằng cách cho chúng tham gia nhiều hoạt động nghệ thuật khác nhau, như viết lách, làm thơ, vẽ, làm đồ gốm,... Điều này có thể áp dụng được cho trẻ mọi lứa tuổi.'
        }
    },
    4: {
        1: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.ONE + BIRTH_DATE_NUMBER_SUBSECTION.FOUR,
            meaning: 'Những người có Biểu đồ ngày sinh có một số 1 thường gặp một chút khó khăn trong việc thể hiện bản thân qua ngôn ngữ. Điều này không có nghĩa là họ không thể nói chuyện một cách suôn sẻ, mà là họ khó diễn đạt được cảm xúc nội tâm của mình.\n' + '\n' + 'Họ có thể nói rất lưu loát và đầy thuyết phục về các đề tài không liên quan đến diễn đạt cảm xúc cá nhân, nhưng thường không biết cách biểu đạt bản thân hoặc diễn tả những gì mình đang cảm thấy. Chỉ khi nào họ học được cách làm chủ bản thân - kết quả của quá trình trưởng thành và thấu hiểu - thì điều này mới được cải thiện. Đôi khi họ sẽ cố ý nói ra những lời hoàn toàn trái ngược với suy nghĩ thật sự của mình như một kiểu phản ứng tự vệ - tức là họ Cố ý làm tổn thương hoặc xúc phạm người khác để tự bảo vệ bản thân mình. Điều này khiến vấn đề ban đầu trở nên nghiêm trọng hơn và gây ra những cuộc tranh cãi gay gắt. Họ cần tập suy nghĩ cẩn trọng trước khi phát biểu, và họ có thể làm được điều ấy bằng cách học kiểm soát phản ứng của bản thân trước các ý kiến, lời phê bình, vì những lời nói đã nói ra thì không thể thu hồi và cảm giác tổn thương rất khó được chữa lành. Để cải thiện hạn chế này, hãy lấy một quyển số trắng và ghi ngày tháng hiện tại. Sau đó, vào buổi tối, trước khi đi ngủ, hãy dành vài phút viết ra những suy nghĩ và cảm nhận của bạn về ngày hôm nay. Nhớ ghi rõ cả những việc bạn vốn dĩ muốn làm, những lời bạn vốn dĩ muốn nói, nhưng rốt cuộc đã không thực hiện được và những điều bạn đã nói hay lỡ làm mà bạn ước gì bạn đã không làm hay nói. Buổi sáng hôm sau, bạn hãy đọc to toàn bộ nội dung đó trước một tấm gương lớn và quan sát ngôn ngữ cơ thể bạn.\n' +
                '\n' + 'Hãy làm điều này thường xuyên và bạn sẽ nhìn thấy sự tự tin trong việc diễn đạt bản thân được cải thiện thấy rõ, về cuộc sống, những người có một số 1 thường cảm thấy thiếu một điều gì đó trong cuộc sống, mặc dù thoạt nhìn họ rất đủ đầy ở một số mặt.',
        },
        2: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.TWO + BIRTH_DATE_NUMBER_SUBSECTION.FOUR,
            meaning: 'Người có hai số 1 (11) trong Biểu đồ ngày sinh là người may mắn nhất trong cả nhóm, bởi sự cân bằng trời cho trong việc diễn đạt nội tâm. Đây là một đặc điểm nên được sử dụng một cách khôn ngoan - không bao giờ lạm dụng nó cho mục đích thao túng người khác. (Đồng thời hãy nhớ đừng mất kiên nhẫn với những người không may mắn không có hai số 1 giống bạn, đặc biệt nếu đó là người yêu hoặc người bạn đời của bạn.) Người có hai số 1 thường có khả năng nhìn nhận các vấn đề hay các cuộc tranh luận theo cả hai mặt, và vì vậy họ hoàn toàn có khả năng chuyển sang hướng đối lập trong một cuộc thảo luận nếu quan điểm của bên đó có vẻ có giá trị hơn. Điều này giúp họ không bị sa vào tư duy bảo thủ, thứ khiến tầm hiểu biết bị giới hạn một chiều, và vì thế bản thân họ cũng thường ít khi bắt bẻ những “ lỗi sai ” của người khác. Có thể nói người có hai số 1 trong biểu đồ thường dễ có cuộc sống cân bằng, an vui, bất kể cuộc sống có diễn ra thế nào. Về nhận định này, tôi có hai điều muốn chia sẻ kỹ hơn : Một Biểu đồ ngày sinh sẽ bao gồm rất nhiều yếu tố chi tiết bên trong, yếu tố này hòa quyện với yếu tố kia, hay yếu tố này mâu thuẫn với yếu tố kia, làm giảm giá trị của yếu tố kia.\n' +
                '\n' + 'Ví dụ, nếu một người có được hai số 1 nhưng lại trống hoàn toàn cột giữa (4-5-6 - mang ý nghĩa Mũi tên uất giận, vì họ mãi không đạt được điều mình khát khao muốn có) , và đặc biệt nếu có thêm số 7 (hay 77, hay 777) thì người đó rất dễ gặp phải một trong những điều bất ý lớn trong các khía cạnh: sức khỏe, tiền tài, tình yêu, sự nghiệp ... Nhưng nhờ sức mạnh của hai số 1, người đó vẫn hay dùng lòng tin để tiếp thu cái mới, từ đó khiến bản thân gặp nhiều thiệt thòi. Tuy nhiên, nhờ trong Biểu đồ ngày sinh của tôi có hai số 1 (11) nên tôi có được một đặc điểm (như đã đề cập ở trên) : dễ dàng nhìn được hai mặt của một vấn đề, chịu thay đổi quan điểm một khi thấy các quan điểm khác cũng đúng hoặc có giá trị. Điều này đặc biệt ý nghĩa với các vấn đề mang tính trực giác, đòi hỏi sự hiểu biết sâu xa hơn những gì mắt thường nhìn thấy. Cho nên hiện giờ tôi đã thôi không còn dùng khái niệm “ thấy mới tin ” nữa, mà bắt đầu lắng tâm mình hơn, mỗi ngày một phát huy trực giác (còn gọi là “ con mắt ” bên trong) để cảm mọi việc, nhờ vậy tôi có thể tiếp thu nhiều cái mới mẻ hơn, rộng lớn hơn. Như vậy, hai số 1 (11) đã giúp tôi hóa giải bớt tính “ cứng đầu ” của Mũi tên 1-4-7 đó.\n' +
                '\n' + 'Trở lại với những đặc điểm nổi bật của hai số 1 (11) :\n' + '\n' + 'Chính nhờ những yếu tố tích cực, dung hòa và cân bằng này mà người có hai số 1 trong biểu đồ dễ trở thành các chính trị gia thành công hoặc người của công chúng, người nổi tiếng. Yếu tố hai số 1 làm nổi bật nhận thức về con người, cũng như cách biểu đạt bản thân và khả năng nhìn nhận vấn đề một cách đa chiều, không phiến diện, giúp giảm thiểu khả năng bị hiểu lầm.',
        },
        3: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.THREE + BIRTH_DATE_NUMBER_SUBSECTION.FOUR,
            meaning: 'Với những người có ba số 1 trong Biểu đồ ngày sinh, có hai khả năng khá đối lập xảy ra trong thực tế. Khả năng thường gặp nhất là những người này thuộc dạng nói rất nhiều, thường có mặt trong rất nhiều cuộc trò chuyện sôi nổi mà trong đó họ trở nên nổi bật và thú vị. Nhìn chung họ thấy cuộc sống dễ chịu và thường cố gắng chia sẻ điều đó với những người xung quanh, Nhóm thứ hai là những người cũng có ba số 1 nhưng lại không có số nào ở Trục ngang Tinh thần (tức là không có các số 2-5-8) . Những người này khá im lặng, hướng nội, bẽn lẽn, đặc biệt là với người lạ. Tuy nhiên, họ có thể hoạt bát và nói nhiều khi trò chuyện với bạn bè thân thiết hoặc người thân trong nhà - đó là những lúc họ cảm thấy thoải mái. Những người này thường dễ diễn đạt cảm xúc hay nội tâm của mình bằng cách viết, vì khi đó dòng suy nghĩ của họ liền mạch hơn, không bị cản trở bởi sự nhạy cảm quá mức của họ. Nếu bạn thuộc nhóm này mà chưa biết sức mạnh khả năng viết lách của mình, hãy thử xem sao. Hãy xem viết lách là một cách để tập diễn đạt bản thân cho trôi chảy, khơi thông những cảm xúc rối rắm tắc nghẽn trong lòng, cũng như là một cách để tự chữa lành. Ngoài ra, còn một khả năng nữa ở những người có ba số 1 mà bản thân tôi quan sát thấy, đó là tâm trạng lúc vui lúc buồn. Tùy theo những yếu tố khác trong Biểu đồ ngày sinh mà tỷ lệ vui buồn sẽ gia giảm khác nhau, tốt nhất thì được 5/5, còn không thì 4/6, không nữa thì 3/7, lúc vui họ có xu hướng nói rất nhiều, lúc buồn thì ngồi im, không quan tâm tới ai.',
        },
        4: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.FOUR + BIRTH_DATE_NUMBER_SUBSECTION.FOUR,
            meaning: 'Người có bốn số 1 trong ngày sinh thường gặp trục trặc với vấn đề diễn đạt bằng lời, và vì vậy, rất dễ bị người khác hiểu lầm. Nhưng cuộc sống nhanh chóng dạy họ giấu đi những cảm xúc rối rắm bằng một nụ cười, cho dù họ có khuynh hướng dẫn tiếp tục chịu đựng bên trong cho đến khi tự có ý thức giải tỏa những cảm xúc đó và sống lẹ làng hơn. Nói một cách dễ hiểu, những người có bốn số 1 thường tự làm mình khổ tâm. Số 1 mang đặc tính về “ cái tôi ” của mỗi người, vậy nên hãy tưởng tượng một người có đến bốn lần “ cái tôi ” như vậy sẽ như thế nào. Họ có “ cái tôi rất mạnh, nhưng rất khó diễn đạt những cảm giác sâu đậm như vậy về bản thân mình. Vì vậy, Thầy David khuyên: vì hạnh phúc của chính mình và của những người thân, những người có bốn số 1 phải học cách kiểm soát cảm xúc của mình. Khi họ thả lỏng hơn, bớt căng thẳng, bớt thiếu tự tin (đôi khi họ không nhận ra điều này, mà trái lại, họ có thể cảm thấy mình quá tự tin là đằng khác), họ sẽ cảm thấy ít bị cản trở hơn và diễn đạt cảm xúc của mình một cách thoải mái hơn, thay vì cứ đè nén những sầu muộn, rối rắm trong nội tâm của mình.',
        },
        5: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.FIVE + BIRTH_DATE_NUMBER_SUBSECTION.FOUR,
            meaning: 'Với năm hay sáu số 1 trên Biểu đồ ngày sinh, “ cái tôi ” thường bị đè nén để giảm bớt các khó khăn trong việc diễn đạt cảm xúc cá nhân. Những người trẻ tuổi thuộc nhóm này thường cảm thấy buồn vì bị mọi người xung quanh hiểu lầm. Điều này dẫn đến sự tách rời, từ đó gây gia sự cô độc. Họ có thể phát triển theo hướng bị ám ảnh với ngoại hình và hành động của mình, cũng như thường gắn rất nhiều gương trong nhà nhưng lại có xu hướng giấu chúng đi để tránh người khác nghĩ họ quá tự tôn. Nhưng họ vẫn bí mật ngắm mình trong gương mỗi khi có dịp. Tính vị kỷ và “ tự lừa mình ” này có thể gây ra sự mất cân bằng về tâm thần, chúng ta có thể giúp trẻ thuộc nhóm có quá nhiều số 1 gia tăng nhận thức bằng cách cho chúng tham gia nhiều hoạt động nghệ thuật khác nhau, như viết lách, làm thơ, vẽ, làm đồ gốm,... Điều này có thể áp dụng được cho trẻ mọi lứa tuổi.'
        }
    },
    5: {
        1: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.ONE + BIRTH_DATE_NUMBER_SUBSECTION.FIVE,
            meaning: 'Những người có Biểu đồ ngày sinh có một số 1 thường gặp một chút khó khăn trong việc thể hiện bản thân qua ngôn ngữ. Điều này không có nghĩa là họ không thể nói chuyện một cách suôn sẻ, mà là họ khó diễn đạt được cảm xúc nội tâm của mình.\n' + '\n' + 'Họ có thể nói rất lưu loát và đầy thuyết phục về các đề tài không liên quan đến diễn đạt cảm xúc cá nhân, nhưng thường không biết cách biểu đạt bản thân hoặc diễn tả những gì mình đang cảm thấy. Chỉ khi nào họ học được cách làm chủ bản thân - kết quả của quá trình trưởng thành và thấu hiểu - thì điều này mới được cải thiện. Đôi khi họ sẽ cố ý nói ra những lời hoàn toàn trái ngược với suy nghĩ thật sự của mình như một kiểu phản ứng tự vệ - tức là họ Cố ý làm tổn thương hoặc xúc phạm người khác để tự bảo vệ bản thân mình. Điều này khiến vấn đề ban đầu trở nên nghiêm trọng hơn và gây ra những cuộc tranh cãi gay gắt. Họ cần tập suy nghĩ cẩn trọng trước khi phát biểu, và họ có thể làm được điều ấy bằng cách học kiểm soát phản ứng của bản thân trước các ý kiến, lời phê bình, vì những lời nói đã nói ra thì không thể thu hồi và cảm giác tổn thương rất khó được chữa lành. Để cải thiện hạn chế này, hãy lấy một quyển số trắng và ghi ngày tháng hiện tại. Sau đó, vào buổi tối, trước khi đi ngủ, hãy dành vài phút viết ra những suy nghĩ và cảm nhận của bạn về ngày hôm nay. Nhớ ghi rõ cả những việc bạn vốn dĩ muốn làm, những lời bạn vốn dĩ muốn nói, nhưng rốt cuộc đã không thực hiện được và những điều bạn đã nói hay lỡ làm mà bạn ước gì bạn đã không làm hay nói. Buổi sáng hôm sau, bạn hãy đọc to toàn bộ nội dung đó trước một tấm gương lớn và quan sát ngôn ngữ cơ thể bạn.\n' +
                '\n' + 'Hãy làm điều này thường xuyên và bạn sẽ nhìn thấy sự tự tin trong việc diễn đạt bản thân được cải thiện thấy rõ, về cuộc sống, những người có một số 1 thường cảm thấy thiếu một điều gì đó trong cuộc sống, mặc dù thoạt nhìn họ rất đủ đầy ở một số mặt.',
        },
        2: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.TWO + BIRTH_DATE_NUMBER_SUBSECTION.FIVE,
            meaning: 'Người có hai số 1 (11) trong Biểu đồ ngày sinh là người may mắn nhất trong cả nhóm, bởi sự cân bằng trời cho trong việc diễn đạt nội tâm. Đây là một đặc điểm nên được sử dụng một cách khôn ngoan - không bao giờ lạm dụng nó cho mục đích thao túng người khác. (Đồng thời hãy nhớ đừng mất kiên nhẫn với những người không may mắn không có hai số 1 giống bạn, đặc biệt nếu đó là người yêu hoặc người bạn đời của bạn.) Người có hai số 1 thường có khả năng nhìn nhận các vấn đề hay các cuộc tranh luận theo cả hai mặt, và vì vậy họ hoàn toàn có khả năng chuyển sang hướng đối lập trong một cuộc thảo luận nếu quan điểm của bên đó có vẻ có giá trị hơn. Điều này giúp họ không bị sa vào tư duy bảo thủ, thứ khiến tầm hiểu biết bị giới hạn một chiều, và vì thế bản thân họ cũng thường ít khi bắt bẻ những “ lỗi sai ” của người khác. Có thể nói người có hai số 1 trong biểu đồ thường dễ có cuộc sống cân bằng, an vui, bất kể cuộc sống có diễn ra thế nào. Về nhận định này, tôi có hai điều muốn chia sẻ kỹ hơn : Một Biểu đồ ngày sinh sẽ bao gồm rất nhiều yếu tố chi tiết bên trong, yếu tố này hòa quyện với yếu tố kia, hay yếu tố này mâu thuẫn với yếu tố kia, làm giảm giá trị của yếu tố kia.\n' +
                '\n' + 'Ví dụ, nếu một người có được hai số 1 nhưng lại trống hoàn toàn cột giữa (4-5-6 - mang ý nghĩa Mũi tên uất giận, vì họ mãi không đạt được điều mình khát khao muốn có) , và đặc biệt nếu có thêm số 7 (hay 77, hay 777) thì người đó rất dễ gặp phải một trong những điều bất ý lớn trong các khía cạnh: sức khỏe, tiền tài, tình yêu, sự nghiệp ... Nhưng nhờ sức mạnh của hai số 1, người đó vẫn hay dùng lòng tin để tiếp thu cái mới, từ đó khiến bản thân gặp nhiều thiệt thòi. Tuy nhiên, nhờ trong Biểu đồ ngày sinh của tôi có hai số 1 (11) nên tôi có được một đặc điểm (như đã đề cập ở trên) : dễ dàng nhìn được hai mặt của một vấn đề, chịu thay đổi quan điểm một khi thấy các quan điểm khác cũng đúng hoặc có giá trị. Điều này đặc biệt ý nghĩa với các vấn đề mang tính trực giác, đòi hỏi sự hiểu biết sâu xa hơn những gì mắt thường nhìn thấy. Cho nên hiện giờ tôi đã thôi không còn dùng khái niệm “ thấy mới tin ” nữa, mà bắt đầu lắng tâm mình hơn, mỗi ngày một phát huy trực giác (còn gọi là “ con mắt ” bên trong) để cảm mọi việc, nhờ vậy tôi có thể tiếp thu nhiều cái mới mẻ hơn, rộng lớn hơn. Như vậy, hai số 1 (11) đã giúp tôi hóa giải bớt tính “ cứng đầu ” của Mũi tên 1-4-7 đó.\n' +
                '\n' + 'Trở lại với những đặc điểm nổi bật của hai số 1 (11) :\n' + '\n' + 'Chính nhờ những yếu tố tích cực, dung hòa và cân bằng này mà người có hai số 1 trong biểu đồ dễ trở thành các chính trị gia thành công hoặc người của công chúng, người nổi tiếng. Yếu tố hai số 1 làm nổi bật nhận thức về con người, cũng như cách biểu đạt bản thân và khả năng nhìn nhận vấn đề một cách đa chiều, không phiến diện, giúp giảm thiểu khả năng bị hiểu lầm.',
        },
        3: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.THREE + BIRTH_DATE_NUMBER_SUBSECTION.FIVE,
            meaning: 'Với những người có ba số 1 trong Biểu đồ ngày sinh, có hai khả năng khá đối lập xảy ra trong thực tế. Khả năng thường gặp nhất là những người này thuộc dạng nói rất nhiều, thường có mặt trong rất nhiều cuộc trò chuyện sôi nổi mà trong đó họ trở nên nổi bật và thú vị. Nhìn chung họ thấy cuộc sống dễ chịu và thường cố gắng chia sẻ điều đó với những người xung quanh, Nhóm thứ hai là những người cũng có ba số 1 nhưng lại không có số nào ở Trục ngang Tinh thần (tức là không có các số 2-5-8) . Những người này khá im lặng, hướng nội, bẽn lẽn, đặc biệt là với người lạ. Tuy nhiên, họ có thể hoạt bát và nói nhiều khi trò chuyện với bạn bè thân thiết hoặc người thân trong nhà - đó là những lúc họ cảm thấy thoải mái. Những người này thường dễ diễn đạt cảm xúc hay nội tâm của mình bằng cách viết, vì khi đó dòng suy nghĩ của họ liền mạch hơn, không bị cản trở bởi sự nhạy cảm quá mức của họ. Nếu bạn thuộc nhóm này mà chưa biết sức mạnh khả năng viết lách của mình, hãy thử xem sao. Hãy xem viết lách là một cách để tập diễn đạt bản thân cho trôi chảy, khơi thông những cảm xúc rối rắm tắc nghẽn trong lòng, cũng như là một cách để tự chữa lành. Ngoài ra, còn một khả năng nữa ở những người có ba số 1 mà bản thân tôi quan sát thấy, đó là tâm trạng lúc vui lúc buồn. Tùy theo những yếu tố khác trong Biểu đồ ngày sinh mà tỷ lệ vui buồn sẽ gia giảm khác nhau, tốt nhất thì được 5/5, còn không thì 4/6, không nữa thì 3/7, lúc vui họ có xu hướng nói rất nhiều, lúc buồn thì ngồi im, không quan tâm tới ai.',
        },
        4: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.FOUR + BIRTH_DATE_NUMBER_SUBSECTION.FIVE,
            meaning: 'Người có bốn số 1 trong ngày sinh thường gặp trục trặc với vấn đề diễn đạt bằng lời, và vì vậy, rất dễ bị người khác hiểu lầm. Nhưng cuộc sống nhanh chóng dạy họ giấu đi những cảm xúc rối rắm bằng một nụ cười, cho dù họ có khuynh hướng dẫn tiếp tục chịu đựng bên trong cho đến khi tự có ý thức giải tỏa những cảm xúc đó và sống lẹ làng hơn. Nói một cách dễ hiểu, những người có bốn số 1 thường tự làm mình khổ tâm. Số 1 mang đặc tính về “ cái tôi ” của mỗi người, vậy nên hãy tưởng tượng một người có đến bốn lần “ cái tôi ” như vậy sẽ như thế nào. Họ có “ cái tôi rất mạnh, nhưng rất khó diễn đạt những cảm giác sâu đậm như vậy về bản thân mình. Vì vậy, Thầy David khuyên: vì hạnh phúc của chính mình và của những người thân, những người có bốn số 1 phải học cách kiểm soát cảm xúc của mình. Khi họ thả lỏng hơn, bớt căng thẳng, bớt thiếu tự tin (đôi khi họ không nhận ra điều này, mà trái lại, họ có thể cảm thấy mình quá tự tin là đằng khác), họ sẽ cảm thấy ít bị cản trở hơn và diễn đạt cảm xúc của mình một cách thoải mái hơn, thay vì cứ đè nén những sầu muộn, rối rắm trong nội tâm của mình.',
        },
        5: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.FIVE + BIRTH_DATE_NUMBER_SUBSECTION.FIVE,
            meaning: 'Với năm hay sáu số 1 trên Biểu đồ ngày sinh, “ cái tôi ” thường bị đè nén để giảm bớt các khó khăn trong việc diễn đạt cảm xúc cá nhân. Những người trẻ tuổi thuộc nhóm này thường cảm thấy buồn vì bị mọi người xung quanh hiểu lầm. Điều này dẫn đến sự tách rời, từ đó gây gia sự cô độc. Họ có thể phát triển theo hướng bị ám ảnh với ngoại hình và hành động của mình, cũng như thường gắn rất nhiều gương trong nhà nhưng lại có xu hướng giấu chúng đi để tránh người khác nghĩ họ quá tự tôn. Nhưng họ vẫn bí mật ngắm mình trong gương mỗi khi có dịp. Tính vị kỷ và “ tự lừa mình ” này có thể gây ra sự mất cân bằng về tâm thần, chúng ta có thể giúp trẻ thuộc nhóm có quá nhiều số 1 gia tăng nhận thức bằng cách cho chúng tham gia nhiều hoạt động nghệ thuật khác nhau, như viết lách, làm thơ, vẽ, làm đồ gốm,... Điều này có thể áp dụng được cho trẻ mọi lứa tuổi.'
        }
    },
    6: {
        1: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.ONE + BIRTH_DATE_NUMBER_SUBSECTION.SIX,
            meaning: 'Những người có Biểu đồ ngày sinh có một số 1 thường gặp một chút khó khăn trong việc thể hiện bản thân qua ngôn ngữ. Điều này không có nghĩa là họ không thể nói chuyện một cách suôn sẻ, mà là họ khó diễn đạt được cảm xúc nội tâm của mình.\n' + '\n' + 'Họ có thể nói rất lưu loát và đầy thuyết phục về các đề tài không liên quan đến diễn đạt cảm xúc cá nhân, nhưng thường không biết cách biểu đạt bản thân hoặc diễn tả những gì mình đang cảm thấy. Chỉ khi nào họ học được cách làm chủ bản thân - kết quả của quá trình trưởng thành và thấu hiểu - thì điều này mới được cải thiện. Đôi khi họ sẽ cố ý nói ra những lời hoàn toàn trái ngược với suy nghĩ thật sự của mình như một kiểu phản ứng tự vệ - tức là họ Cố ý làm tổn thương hoặc xúc phạm người khác để tự bảo vệ bản thân mình. Điều này khiến vấn đề ban đầu trở nên nghiêm trọng hơn và gây ra những cuộc tranh cãi gay gắt. Họ cần tập suy nghĩ cẩn trọng trước khi phát biểu, và họ có thể làm được điều ấy bằng cách học kiểm soát phản ứng của bản thân trước các ý kiến, lời phê bình, vì những lời nói đã nói ra thì không thể thu hồi và cảm giác tổn thương rất khó được chữa lành. Để cải thiện hạn chế này, hãy lấy một quyển số trắng và ghi ngày tháng hiện tại. Sau đó, vào buổi tối, trước khi đi ngủ, hãy dành vài phút viết ra những suy nghĩ và cảm nhận của bạn về ngày hôm nay. Nhớ ghi rõ cả những việc bạn vốn dĩ muốn làm, những lời bạn vốn dĩ muốn nói, nhưng rốt cuộc đã không thực hiện được và những điều bạn đã nói hay lỡ làm mà bạn ước gì bạn đã không làm hay nói. Buổi sáng hôm sau, bạn hãy đọc to toàn bộ nội dung đó trước một tấm gương lớn và quan sát ngôn ngữ cơ thể bạn.\n' +
                '\n' + 'Hãy làm điều này thường xuyên và bạn sẽ nhìn thấy sự tự tin trong việc diễn đạt bản thân được cải thiện thấy rõ, về cuộc sống, những người có một số 1 thường cảm thấy thiếu một điều gì đó trong cuộc sống, mặc dù thoạt nhìn họ rất đủ đầy ở một số mặt.',
        },
        2: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.TWO + BIRTH_DATE_NUMBER_SUBSECTION.SIX,
            meaning: 'Người có hai số 1 (11) trong Biểu đồ ngày sinh là người may mắn nhất trong cả nhóm, bởi sự cân bằng trời cho trong việc diễn đạt nội tâm. Đây là một đặc điểm nên được sử dụng một cách khôn ngoan - không bao giờ lạm dụng nó cho mục đích thao túng người khác. (Đồng thời hãy nhớ đừng mất kiên nhẫn với những người không may mắn không có hai số 1 giống bạn, đặc biệt nếu đó là người yêu hoặc người bạn đời của bạn.) Người có hai số 1 thường có khả năng nhìn nhận các vấn đề hay các cuộc tranh luận theo cả hai mặt, và vì vậy họ hoàn toàn có khả năng chuyển sang hướng đối lập trong một cuộc thảo luận nếu quan điểm của bên đó có vẻ có giá trị hơn. Điều này giúp họ không bị sa vào tư duy bảo thủ, thứ khiến tầm hiểu biết bị giới hạn một chiều, và vì thế bản thân họ cũng thường ít khi bắt bẻ những “ lỗi sai ” của người khác. Có thể nói người có hai số 1 trong biểu đồ thường dễ có cuộc sống cân bằng, an vui, bất kể cuộc sống có diễn ra thế nào. Về nhận định này, tôi có hai điều muốn chia sẻ kỹ hơn : Một Biểu đồ ngày sinh sẽ bao gồm rất nhiều yếu tố chi tiết bên trong, yếu tố này hòa quyện với yếu tố kia, hay yếu tố này mâu thuẫn với yếu tố kia, làm giảm giá trị của yếu tố kia.\n' +
                '\n' + 'Ví dụ, nếu một người có được hai số 1 nhưng lại trống hoàn toàn cột giữa (4-5-6 - mang ý nghĩa Mũi tên uất giận, vì họ mãi không đạt được điều mình khát khao muốn có) , và đặc biệt nếu có thêm số 7 (hay 77, hay 777) thì người đó rất dễ gặp phải một trong những điều bất ý lớn trong các khía cạnh: sức khỏe, tiền tài, tình yêu, sự nghiệp ... Nhưng nhờ sức mạnh của hai số 1, người đó vẫn hay dùng lòng tin để tiếp thu cái mới, từ đó khiến bản thân gặp nhiều thiệt thòi. Tuy nhiên, nhờ trong Biểu đồ ngày sinh của tôi có hai số 1 (11) nên tôi có được một đặc điểm (như đã đề cập ở trên) : dễ dàng nhìn được hai mặt của một vấn đề, chịu thay đổi quan điểm một khi thấy các quan điểm khác cũng đúng hoặc có giá trị. Điều này đặc biệt ý nghĩa với các vấn đề mang tính trực giác, đòi hỏi sự hiểu biết sâu xa hơn những gì mắt thường nhìn thấy. Cho nên hiện giờ tôi đã thôi không còn dùng khái niệm “ thấy mới tin ” nữa, mà bắt đầu lắng tâm mình hơn, mỗi ngày một phát huy trực giác (còn gọi là “ con mắt ” bên trong) để cảm mọi việc, nhờ vậy tôi có thể tiếp thu nhiều cái mới mẻ hơn, rộng lớn hơn. Như vậy, hai số 1 (11) đã giúp tôi hóa giải bớt tính “ cứng đầu ” của Mũi tên 1-4-7 đó.\n' +
                '\n' + 'Trở lại với những đặc điểm nổi bật của hai số 1 (11) :\n' + '\n' + 'Chính nhờ những yếu tố tích cực, dung hòa và cân bằng này mà người có hai số 1 trong biểu đồ dễ trở thành các chính trị gia thành công hoặc người của công chúng, người nổi tiếng. Yếu tố hai số 1 làm nổi bật nhận thức về con người, cũng như cách biểu đạt bản thân và khả năng nhìn nhận vấn đề một cách đa chiều, không phiến diện, giúp giảm thiểu khả năng bị hiểu lầm.',
        },
        3: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.THREE + BIRTH_DATE_NUMBER_SUBSECTION.SIX,
            meaning: 'Với những người có ba số 1 trong Biểu đồ ngày sinh, có hai khả năng khá đối lập xảy ra trong thực tế. Khả năng thường gặp nhất là những người này thuộc dạng nói rất nhiều, thường có mặt trong rất nhiều cuộc trò chuyện sôi nổi mà trong đó họ trở nên nổi bật và thú vị. Nhìn chung họ thấy cuộc sống dễ chịu và thường cố gắng chia sẻ điều đó với những người xung quanh, Nhóm thứ hai là những người cũng có ba số 1 nhưng lại không có số nào ở Trục ngang Tinh thần (tức là không có các số 2-5-8) . Những người này khá im lặng, hướng nội, bẽn lẽn, đặc biệt là với người lạ. Tuy nhiên, họ có thể hoạt bát và nói nhiều khi trò chuyện với bạn bè thân thiết hoặc người thân trong nhà - đó là những lúc họ cảm thấy thoải mái. Những người này thường dễ diễn đạt cảm xúc hay nội tâm của mình bằng cách viết, vì khi đó dòng suy nghĩ của họ liền mạch hơn, không bị cản trở bởi sự nhạy cảm quá mức của họ. Nếu bạn thuộc nhóm này mà chưa biết sức mạnh khả năng viết lách của mình, hãy thử xem sao. Hãy xem viết lách là một cách để tập diễn đạt bản thân cho trôi chảy, khơi thông những cảm xúc rối rắm tắc nghẽn trong lòng, cũng như là một cách để tự chữa lành. Ngoài ra, còn một khả năng nữa ở những người có ba số 1 mà bản thân tôi quan sát thấy, đó là tâm trạng lúc vui lúc buồn. Tùy theo những yếu tố khác trong Biểu đồ ngày sinh mà tỷ lệ vui buồn sẽ gia giảm khác nhau, tốt nhất thì được 5/5, còn không thì 4/6, không nữa thì 3/7, lúc vui họ có xu hướng nói rất nhiều, lúc buồn thì ngồi im, không quan tâm tới ai.',
        },
        4: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.FOUR + BIRTH_DATE_NUMBER_SUBSECTION.SIX,
            meaning: 'Người có bốn số 1 trong ngày sinh thường gặp trục trặc với vấn đề diễn đạt bằng lời, và vì vậy, rất dễ bị người khác hiểu lầm. Nhưng cuộc sống nhanh chóng dạy họ giấu đi những cảm xúc rối rắm bằng một nụ cười, cho dù họ có khuynh hướng dẫn tiếp tục chịu đựng bên trong cho đến khi tự có ý thức giải tỏa những cảm xúc đó và sống lẹ làng hơn. Nói một cách dễ hiểu, những người có bốn số 1 thường tự làm mình khổ tâm. Số 1 mang đặc tính về “ cái tôi ” của mỗi người, vậy nên hãy tưởng tượng một người có đến bốn lần “ cái tôi ” như vậy sẽ như thế nào. Họ có “ cái tôi rất mạnh, nhưng rất khó diễn đạt những cảm giác sâu đậm như vậy về bản thân mình. Vì vậy, Thầy David khuyên: vì hạnh phúc của chính mình và của những người thân, những người có bốn số 1 phải học cách kiểm soát cảm xúc của mình. Khi họ thả lỏng hơn, bớt căng thẳng, bớt thiếu tự tin (đôi khi họ không nhận ra điều này, mà trái lại, họ có thể cảm thấy mình quá tự tin là đằng khác), họ sẽ cảm thấy ít bị cản trở hơn và diễn đạt cảm xúc của mình một cách thoải mái hơn, thay vì cứ đè nén những sầu muộn, rối rắm trong nội tâm của mình.',
        },
        5: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.FIVE + BIRTH_DATE_NUMBER_SUBSECTION.SIX,
            meaning: 'Với năm hay sáu số 1 trên Biểu đồ ngày sinh, “ cái tôi ” thường bị đè nén để giảm bớt các khó khăn trong việc diễn đạt cảm xúc cá nhân. Những người trẻ tuổi thuộc nhóm này thường cảm thấy buồn vì bị mọi người xung quanh hiểu lầm. Điều này dẫn đến sự tách rời, từ đó gây gia sự cô độc. Họ có thể phát triển theo hướng bị ám ảnh với ngoại hình và hành động của mình, cũng như thường gắn rất nhiều gương trong nhà nhưng lại có xu hướng giấu chúng đi để tránh người khác nghĩ họ quá tự tôn. Nhưng họ vẫn bí mật ngắm mình trong gương mỗi khi có dịp. Tính vị kỷ và “ tự lừa mình ” này có thể gây ra sự mất cân bằng về tâm thần, chúng ta có thể giúp trẻ thuộc nhóm có quá nhiều số 1 gia tăng nhận thức bằng cách cho chúng tham gia nhiều hoạt động nghệ thuật khác nhau, như viết lách, làm thơ, vẽ, làm đồ gốm,... Điều này có thể áp dụng được cho trẻ mọi lứa tuổi.'
        }
    },
    7: {
        1: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.ONE + BIRTH_DATE_NUMBER_SUBSECTION.SEVEN,
            meaning: 'Những người có Biểu đồ ngày sinh có một số 1 thường gặp một chút khó khăn trong việc thể hiện bản thân qua ngôn ngữ. Điều này không có nghĩa là họ không thể nói chuyện một cách suôn sẻ, mà là họ khó diễn đạt được cảm xúc nội tâm của mình.\n' + '\n' + 'Họ có thể nói rất lưu loát và đầy thuyết phục về các đề tài không liên quan đến diễn đạt cảm xúc cá nhân, nhưng thường không biết cách biểu đạt bản thân hoặc diễn tả những gì mình đang cảm thấy. Chỉ khi nào họ học được cách làm chủ bản thân - kết quả của quá trình trưởng thành và thấu hiểu - thì điều này mới được cải thiện. Đôi khi họ sẽ cố ý nói ra những lời hoàn toàn trái ngược với suy nghĩ thật sự của mình như một kiểu phản ứng tự vệ - tức là họ Cố ý làm tổn thương hoặc xúc phạm người khác để tự bảo vệ bản thân mình. Điều này khiến vấn đề ban đầu trở nên nghiêm trọng hơn và gây ra những cuộc tranh cãi gay gắt. Họ cần tập suy nghĩ cẩn trọng trước khi phát biểu, và họ có thể làm được điều ấy bằng cách học kiểm soát phản ứng của bản thân trước các ý kiến, lời phê bình, vì những lời nói đã nói ra thì không thể thu hồi và cảm giác tổn thương rất khó được chữa lành. Để cải thiện hạn chế này, hãy lấy một quyển số trắng và ghi ngày tháng hiện tại. Sau đó, vào buổi tối, trước khi đi ngủ, hãy dành vài phút viết ra những suy nghĩ và cảm nhận của bạn về ngày hôm nay. Nhớ ghi rõ cả những việc bạn vốn dĩ muốn làm, những lời bạn vốn dĩ muốn nói, nhưng rốt cuộc đã không thực hiện được và những điều bạn đã nói hay lỡ làm mà bạn ước gì bạn đã không làm hay nói. Buổi sáng hôm sau, bạn hãy đọc to toàn bộ nội dung đó trước một tấm gương lớn và quan sát ngôn ngữ cơ thể bạn.\n' +
                '\n' + 'Hãy làm điều này thường xuyên và bạn sẽ nhìn thấy sự tự tin trong việc diễn đạt bản thân được cải thiện thấy rõ, về cuộc sống, những người có một số 1 thường cảm thấy thiếu một điều gì đó trong cuộc sống, mặc dù thoạt nhìn họ rất đủ đầy ở một số mặt.',
        },
        2: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.TWO + BIRTH_DATE_NUMBER_SUBSECTION.SEVEN,
            meaning: 'Người có hai số 1 (11) trong Biểu đồ ngày sinh là người may mắn nhất trong cả nhóm, bởi sự cân bằng trời cho trong việc diễn đạt nội tâm. Đây là một đặc điểm nên được sử dụng một cách khôn ngoan - không bao giờ lạm dụng nó cho mục đích thao túng người khác. (Đồng thời hãy nhớ đừng mất kiên nhẫn với những người không may mắn không có hai số 1 giống bạn, đặc biệt nếu đó là người yêu hoặc người bạn đời của bạn.) Người có hai số 1 thường có khả năng nhìn nhận các vấn đề hay các cuộc tranh luận theo cả hai mặt, và vì vậy họ hoàn toàn có khả năng chuyển sang hướng đối lập trong một cuộc thảo luận nếu quan điểm của bên đó có vẻ có giá trị hơn. Điều này giúp họ không bị sa vào tư duy bảo thủ, thứ khiến tầm hiểu biết bị giới hạn một chiều, và vì thế bản thân họ cũng thường ít khi bắt bẻ những “ lỗi sai ” của người khác. Có thể nói người có hai số 1 trong biểu đồ thường dễ có cuộc sống cân bằng, an vui, bất kể cuộc sống có diễn ra thế nào. Về nhận định này, tôi có hai điều muốn chia sẻ kỹ hơn : Một Biểu đồ ngày sinh sẽ bao gồm rất nhiều yếu tố chi tiết bên trong, yếu tố này hòa quyện với yếu tố kia, hay yếu tố này mâu thuẫn với yếu tố kia, làm giảm giá trị của yếu tố kia.\n' +
                '\n' + 'Ví dụ, nếu một người có được hai số 1 nhưng lại trống hoàn toàn cột giữa (4-5-6 - mang ý nghĩa Mũi tên uất giận, vì họ mãi không đạt được điều mình khát khao muốn có) , và đặc biệt nếu có thêm số 7 (hay 77, hay 777) thì người đó rất dễ gặp phải một trong những điều bất ý lớn trong các khía cạnh: sức khỏe, tiền tài, tình yêu, sự nghiệp ... Nhưng nhờ sức mạnh của hai số 1, người đó vẫn hay dùng lòng tin để tiếp thu cái mới, từ đó khiến bản thân gặp nhiều thiệt thòi. Tuy nhiên, nhờ trong Biểu đồ ngày sinh của tôi có hai số 1 (11) nên tôi có được một đặc điểm (như đã đề cập ở trên) : dễ dàng nhìn được hai mặt của một vấn đề, chịu thay đổi quan điểm một khi thấy các quan điểm khác cũng đúng hoặc có giá trị. Điều này đặc biệt ý nghĩa với các vấn đề mang tính trực giác, đòi hỏi sự hiểu biết sâu xa hơn những gì mắt thường nhìn thấy. Cho nên hiện giờ tôi đã thôi không còn dùng khái niệm “ thấy mới tin ” nữa, mà bắt đầu lắng tâm mình hơn, mỗi ngày một phát huy trực giác (còn gọi là “ con mắt ” bên trong) để cảm mọi việc, nhờ vậy tôi có thể tiếp thu nhiều cái mới mẻ hơn, rộng lớn hơn. Như vậy, hai số 1 (11) đã giúp tôi hóa giải bớt tính “ cứng đầu ” của Mũi tên 1-4-7 đó.\n' +
                '\n' + 'Trở lại với những đặc điểm nổi bật của hai số 1 (11) :\n' + '\n' + 'Chính nhờ những yếu tố tích cực, dung hòa và cân bằng này mà người có hai số 1 trong biểu đồ dễ trở thành các chính trị gia thành công hoặc người của công chúng, người nổi tiếng. Yếu tố hai số 1 làm nổi bật nhận thức về con người, cũng như cách biểu đạt bản thân và khả năng nhìn nhận vấn đề một cách đa chiều, không phiến diện, giúp giảm thiểu khả năng bị hiểu lầm.',
        },
        3: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.THREE + BIRTH_DATE_NUMBER_SUBSECTION.SEVEN,
            meaning: 'Với những người có ba số 1 trong Biểu đồ ngày sinh, có hai khả năng khá đối lập xảy ra trong thực tế. Khả năng thường gặp nhất là những người này thuộc dạng nói rất nhiều, thường có mặt trong rất nhiều cuộc trò chuyện sôi nổi mà trong đó họ trở nên nổi bật và thú vị. Nhìn chung họ thấy cuộc sống dễ chịu và thường cố gắng chia sẻ điều đó với những người xung quanh, Nhóm thứ hai là những người cũng có ba số 1 nhưng lại không có số nào ở Trục ngang Tinh thần (tức là không có các số 2-5-8) . Những người này khá im lặng, hướng nội, bẽn lẽn, đặc biệt là với người lạ. Tuy nhiên, họ có thể hoạt bát và nói nhiều khi trò chuyện với bạn bè thân thiết hoặc người thân trong nhà - đó là những lúc họ cảm thấy thoải mái. Những người này thường dễ diễn đạt cảm xúc hay nội tâm của mình bằng cách viết, vì khi đó dòng suy nghĩ của họ liền mạch hơn, không bị cản trở bởi sự nhạy cảm quá mức của họ. Nếu bạn thuộc nhóm này mà chưa biết sức mạnh khả năng viết lách của mình, hãy thử xem sao. Hãy xem viết lách là một cách để tập diễn đạt bản thân cho trôi chảy, khơi thông những cảm xúc rối rắm tắc nghẽn trong lòng, cũng như là một cách để tự chữa lành. Ngoài ra, còn một khả năng nữa ở những người có ba số 1 mà bản thân tôi quan sát thấy, đó là tâm trạng lúc vui lúc buồn. Tùy theo những yếu tố khác trong Biểu đồ ngày sinh mà tỷ lệ vui buồn sẽ gia giảm khác nhau, tốt nhất thì được 5/5, còn không thì 4/6, không nữa thì 3/7, lúc vui họ có xu hướng nói rất nhiều, lúc buồn thì ngồi im, không quan tâm tới ai.',
        },
        4: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.FOUR + BIRTH_DATE_NUMBER_SUBSECTION.SEVEN,
            meaning: 'Người có bốn số 1 trong ngày sinh thường gặp trục trặc với vấn đề diễn đạt bằng lời, và vì vậy, rất dễ bị người khác hiểu lầm. Nhưng cuộc sống nhanh chóng dạy họ giấu đi những cảm xúc rối rắm bằng một nụ cười, cho dù họ có khuynh hướng dẫn tiếp tục chịu đựng bên trong cho đến khi tự có ý thức giải tỏa những cảm xúc đó và sống lẹ làng hơn. Nói một cách dễ hiểu, những người có bốn số 1 thường tự làm mình khổ tâm. Số 1 mang đặc tính về “ cái tôi ” của mỗi người, vậy nên hãy tưởng tượng một người có đến bốn lần “ cái tôi ” như vậy sẽ như thế nào. Họ có “ cái tôi rất mạnh, nhưng rất khó diễn đạt những cảm giác sâu đậm như vậy về bản thân mình. Vì vậy, Thầy David khuyên: vì hạnh phúc của chính mình và của những người thân, những người có bốn số 1 phải học cách kiểm soát cảm xúc của mình. Khi họ thả lỏng hơn, bớt căng thẳng, bớt thiếu tự tin (đôi khi họ không nhận ra điều này, mà trái lại, họ có thể cảm thấy mình quá tự tin là đằng khác), họ sẽ cảm thấy ít bị cản trở hơn và diễn đạt cảm xúc của mình một cách thoải mái hơn, thay vì cứ đè nén những sầu muộn, rối rắm trong nội tâm của mình.',
        },
        5: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.FIVE + BIRTH_DATE_NUMBER_SUBSECTION.SEVEN,
            meaning: 'Với năm hay sáu số 1 trên Biểu đồ ngày sinh, “ cái tôi ” thường bị đè nén để giảm bớt các khó khăn trong việc diễn đạt cảm xúc cá nhân. Những người trẻ tuổi thuộc nhóm này thường cảm thấy buồn vì bị mọi người xung quanh hiểu lầm. Điều này dẫn đến sự tách rời, từ đó gây gia sự cô độc. Họ có thể phát triển theo hướng bị ám ảnh với ngoại hình và hành động của mình, cũng như thường gắn rất nhiều gương trong nhà nhưng lại có xu hướng giấu chúng đi để tránh người khác nghĩ họ quá tự tôn. Nhưng họ vẫn bí mật ngắm mình trong gương mỗi khi có dịp. Tính vị kỷ và “ tự lừa mình ” này có thể gây ra sự mất cân bằng về tâm thần, chúng ta có thể giúp trẻ thuộc nhóm có quá nhiều số 1 gia tăng nhận thức bằng cách cho chúng tham gia nhiều hoạt động nghệ thuật khác nhau, như viết lách, làm thơ, vẽ, làm đồ gốm,... Điều này có thể áp dụng được cho trẻ mọi lứa tuổi.'
        }
    },
    8: {
        1: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.ONE + BIRTH_DATE_NUMBER_SUBSECTION.EIGHT,
            meaning: 'Những người có Biểu đồ ngày sinh có một số 1 thường gặp một chút khó khăn trong việc thể hiện bản thân qua ngôn ngữ. Điều này không có nghĩa là họ không thể nói chuyện một cách suôn sẻ, mà là họ khó diễn đạt được cảm xúc nội tâm của mình.\n' + '\n' + 'Họ có thể nói rất lưu loát và đầy thuyết phục về các đề tài không liên quan đến diễn đạt cảm xúc cá nhân, nhưng thường không biết cách biểu đạt bản thân hoặc diễn tả những gì mình đang cảm thấy. Chỉ khi nào họ học được cách làm chủ bản thân - kết quả của quá trình trưởng thành và thấu hiểu - thì điều này mới được cải thiện. Đôi khi họ sẽ cố ý nói ra những lời hoàn toàn trái ngược với suy nghĩ thật sự của mình như một kiểu phản ứng tự vệ - tức là họ Cố ý làm tổn thương hoặc xúc phạm người khác để tự bảo vệ bản thân mình. Điều này khiến vấn đề ban đầu trở nên nghiêm trọng hơn và gây ra những cuộc tranh cãi gay gắt. Họ cần tập suy nghĩ cẩn trọng trước khi phát biểu, và họ có thể làm được điều ấy bằng cách học kiểm soát phản ứng của bản thân trước các ý kiến, lời phê bình, vì những lời nói đã nói ra thì không thể thu hồi và cảm giác tổn thương rất khó được chữa lành. Để cải thiện hạn chế này, hãy lấy một quyển số trắng và ghi ngày tháng hiện tại. Sau đó, vào buổi tối, trước khi đi ngủ, hãy dành vài phút viết ra những suy nghĩ và cảm nhận của bạn về ngày hôm nay. Nhớ ghi rõ cả những việc bạn vốn dĩ muốn làm, những lời bạn vốn dĩ muốn nói, nhưng rốt cuộc đã không thực hiện được và những điều bạn đã nói hay lỡ làm mà bạn ước gì bạn đã không làm hay nói. Buổi sáng hôm sau, bạn hãy đọc to toàn bộ nội dung đó trước một tấm gương lớn và quan sát ngôn ngữ cơ thể bạn.\n' +
                '\n' + 'Hãy làm điều này thường xuyên và bạn sẽ nhìn thấy sự tự tin trong việc diễn đạt bản thân được cải thiện thấy rõ, về cuộc sống, những người có một số 1 thường cảm thấy thiếu một điều gì đó trong cuộc sống, mặc dù thoạt nhìn họ rất đủ đầy ở một số mặt.',
        },
        2: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.TWO + BIRTH_DATE_NUMBER_SUBSECTION.EIGHT,
            meaning: 'Người có hai số 1 (11) trong Biểu đồ ngày sinh là người may mắn nhất trong cả nhóm, bởi sự cân bằng trời cho trong việc diễn đạt nội tâm. Đây là một đặc điểm nên được sử dụng một cách khôn ngoan - không bao giờ lạm dụng nó cho mục đích thao túng người khác. (Đồng thời hãy nhớ đừng mất kiên nhẫn với những người không may mắn không có hai số 1 giống bạn, đặc biệt nếu đó là người yêu hoặc người bạn đời của bạn.) Người có hai số 1 thường có khả năng nhìn nhận các vấn đề hay các cuộc tranh luận theo cả hai mặt, và vì vậy họ hoàn toàn có khả năng chuyển sang hướng đối lập trong một cuộc thảo luận nếu quan điểm của bên đó có vẻ có giá trị hơn. Điều này giúp họ không bị sa vào tư duy bảo thủ, thứ khiến tầm hiểu biết bị giới hạn một chiều, và vì thế bản thân họ cũng thường ít khi bắt bẻ những “ lỗi sai ” của người khác. Có thể nói người có hai số 1 trong biểu đồ thường dễ có cuộc sống cân bằng, an vui, bất kể cuộc sống có diễn ra thế nào. Về nhận định này, tôi có hai điều muốn chia sẻ kỹ hơn : Một Biểu đồ ngày sinh sẽ bao gồm rất nhiều yếu tố chi tiết bên trong, yếu tố này hòa quyện với yếu tố kia, hay yếu tố này mâu thuẫn với yếu tố kia, làm giảm giá trị của yếu tố kia.\n' +
                '\n' + 'Ví dụ, nếu một người có được hai số 1 nhưng lại trống hoàn toàn cột giữa (4-5-6 - mang ý nghĩa Mũi tên uất giận, vì họ mãi không đạt được điều mình khát khao muốn có) , và đặc biệt nếu có thêm số 7 (hay 77, hay 777) thì người đó rất dễ gặp phải một trong những điều bất ý lớn trong các khía cạnh: sức khỏe, tiền tài, tình yêu, sự nghiệp ... Nhưng nhờ sức mạnh của hai số 1, người đó vẫn hay dùng lòng tin để tiếp thu cái mới, từ đó khiến bản thân gặp nhiều thiệt thòi. Tuy nhiên, nhờ trong Biểu đồ ngày sinh của tôi có hai số 1 (11) nên tôi có được một đặc điểm (như đã đề cập ở trên) : dễ dàng nhìn được hai mặt của một vấn đề, chịu thay đổi quan điểm một khi thấy các quan điểm khác cũng đúng hoặc có giá trị. Điều này đặc biệt ý nghĩa với các vấn đề mang tính trực giác, đòi hỏi sự hiểu biết sâu xa hơn những gì mắt thường nhìn thấy. Cho nên hiện giờ tôi đã thôi không còn dùng khái niệm “ thấy mới tin ” nữa, mà bắt đầu lắng tâm mình hơn, mỗi ngày một phát huy trực giác (còn gọi là “ con mắt ” bên trong) để cảm mọi việc, nhờ vậy tôi có thể tiếp thu nhiều cái mới mẻ hơn, rộng lớn hơn. Như vậy, hai số 1 (11) đã giúp tôi hóa giải bớt tính “ cứng đầu ” của Mũi tên 1-4-7 đó.\n' +
                '\n' + 'Trở lại với những đặc điểm nổi bật của hai số 1 (11) :\n' + '\n' + 'Chính nhờ những yếu tố tích cực, dung hòa và cân bằng này mà người có hai số 1 trong biểu đồ dễ trở thành các chính trị gia thành công hoặc người của công chúng, người nổi tiếng. Yếu tố hai số 1 làm nổi bật nhận thức về con người, cũng như cách biểu đạt bản thân và khả năng nhìn nhận vấn đề một cách đa chiều, không phiến diện, giúp giảm thiểu khả năng bị hiểu lầm.',
        },
        3: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.THREE + BIRTH_DATE_NUMBER_SUBSECTION.EIGHT,
            meaning: 'Với những người có ba số 1 trong Biểu đồ ngày sinh, có hai khả năng khá đối lập xảy ra trong thực tế. Khả năng thường gặp nhất là những người này thuộc dạng nói rất nhiều, thường có mặt trong rất nhiều cuộc trò chuyện sôi nổi mà trong đó họ trở nên nổi bật và thú vị. Nhìn chung họ thấy cuộc sống dễ chịu và thường cố gắng chia sẻ điều đó với những người xung quanh, Nhóm thứ hai là những người cũng có ba số 1 nhưng lại không có số nào ở Trục ngang Tinh thần (tức là không có các số 2-5-8) . Những người này khá im lặng, hướng nội, bẽn lẽn, đặc biệt là với người lạ. Tuy nhiên, họ có thể hoạt bát và nói nhiều khi trò chuyện với bạn bè thân thiết hoặc người thân trong nhà - đó là những lúc họ cảm thấy thoải mái. Những người này thường dễ diễn đạt cảm xúc hay nội tâm của mình bằng cách viết, vì khi đó dòng suy nghĩ của họ liền mạch hơn, không bị cản trở bởi sự nhạy cảm quá mức của họ. Nếu bạn thuộc nhóm này mà chưa biết sức mạnh khả năng viết lách của mình, hãy thử xem sao. Hãy xem viết lách là một cách để tập diễn đạt bản thân cho trôi chảy, khơi thông những cảm xúc rối rắm tắc nghẽn trong lòng, cũng như là một cách để tự chữa lành. Ngoài ra, còn một khả năng nữa ở những người có ba số 1 mà bản thân tôi quan sát thấy, đó là tâm trạng lúc vui lúc buồn. Tùy theo những yếu tố khác trong Biểu đồ ngày sinh mà tỷ lệ vui buồn sẽ gia giảm khác nhau, tốt nhất thì được 5/5, còn không thì 4/6, không nữa thì 3/7, lúc vui họ có xu hướng nói rất nhiều, lúc buồn thì ngồi im, không quan tâm tới ai.',
        },
        4: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.FOUR + BIRTH_DATE_NUMBER_SUBSECTION.EIGHT,
            meaning: 'Người có bốn số 1 trong ngày sinh thường gặp trục trặc với vấn đề diễn đạt bằng lời, và vì vậy, rất dễ bị người khác hiểu lầm. Nhưng cuộc sống nhanh chóng dạy họ giấu đi những cảm xúc rối rắm bằng một nụ cười, cho dù họ có khuynh hướng dẫn tiếp tục chịu đựng bên trong cho đến khi tự có ý thức giải tỏa những cảm xúc đó và sống lẹ làng hơn. Nói một cách dễ hiểu, những người có bốn số 1 thường tự làm mình khổ tâm. Số 1 mang đặc tính về “ cái tôi ” của mỗi người, vậy nên hãy tưởng tượng một người có đến bốn lần “ cái tôi ” như vậy sẽ như thế nào. Họ có “ cái tôi rất mạnh, nhưng rất khó diễn đạt những cảm giác sâu đậm như vậy về bản thân mình. Vì vậy, Thầy David khuyên: vì hạnh phúc của chính mình và của những người thân, những người có bốn số 1 phải học cách kiểm soát cảm xúc của mình. Khi họ thả lỏng hơn, bớt căng thẳng, bớt thiếu tự tin (đôi khi họ không nhận ra điều này, mà trái lại, họ có thể cảm thấy mình quá tự tin là đằng khác), họ sẽ cảm thấy ít bị cản trở hơn và diễn đạt cảm xúc của mình một cách thoải mái hơn, thay vì cứ đè nén những sầu muộn, rối rắm trong nội tâm của mình.',
        },
        5: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.FIVE + BIRTH_DATE_NUMBER_SUBSECTION.EIGHT,
            meaning: 'Với năm hay sáu số 1 trên Biểu đồ ngày sinh, “ cái tôi ” thường bị đè nén để giảm bớt các khó khăn trong việc diễn đạt cảm xúc cá nhân. Những người trẻ tuổi thuộc nhóm này thường cảm thấy buồn vì bị mọi người xung quanh hiểu lầm. Điều này dẫn đến sự tách rời, từ đó gây gia sự cô độc. Họ có thể phát triển theo hướng bị ám ảnh với ngoại hình và hành động của mình, cũng như thường gắn rất nhiều gương trong nhà nhưng lại có xu hướng giấu chúng đi để tránh người khác nghĩ họ quá tự tôn. Nhưng họ vẫn bí mật ngắm mình trong gương mỗi khi có dịp. Tính vị kỷ và “ tự lừa mình ” này có thể gây ra sự mất cân bằng về tâm thần, chúng ta có thể giúp trẻ thuộc nhóm có quá nhiều số 1 gia tăng nhận thức bằng cách cho chúng tham gia nhiều hoạt động nghệ thuật khác nhau, như viết lách, làm thơ, vẽ, làm đồ gốm,... Điều này có thể áp dụng được cho trẻ mọi lứa tuổi.'
        }
    },
    9: {
        1: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.ONE + BIRTH_DATE_NUMBER_SUBSECTION.NINE,
            meaning: 'Những người có Biểu đồ ngày sinh có một số 1 thường gặp một chút khó khăn trong việc thể hiện bản thân qua ngôn ngữ. Điều này không có nghĩa là họ không thể nói chuyện một cách suôn sẻ, mà là họ khó diễn đạt được cảm xúc nội tâm của mình.\n' + '\n' + 'Họ có thể nói rất lưu loát và đầy thuyết phục về các đề tài không liên quan đến diễn đạt cảm xúc cá nhân, nhưng thường không biết cách biểu đạt bản thân hoặc diễn tả những gì mình đang cảm thấy. Chỉ khi nào họ học được cách làm chủ bản thân - kết quả của quá trình trưởng thành và thấu hiểu - thì điều này mới được cải thiện. Đôi khi họ sẽ cố ý nói ra những lời hoàn toàn trái ngược với suy nghĩ thật sự của mình như một kiểu phản ứng tự vệ - tức là họ Cố ý làm tổn thương hoặc xúc phạm người khác để tự bảo vệ bản thân mình. Điều này khiến vấn đề ban đầu trở nên nghiêm trọng hơn và gây ra những cuộc tranh cãi gay gắt. Họ cần tập suy nghĩ cẩn trọng trước khi phát biểu, và họ có thể làm được điều ấy bằng cách học kiểm soát phản ứng của bản thân trước các ý kiến, lời phê bình, vì những lời nói đã nói ra thì không thể thu hồi và cảm giác tổn thương rất khó được chữa lành. Để cải thiện hạn chế này, hãy lấy một quyển số trắng và ghi ngày tháng hiện tại. Sau đó, vào buổi tối, trước khi đi ngủ, hãy dành vài phút viết ra những suy nghĩ và cảm nhận của bạn về ngày hôm nay. Nhớ ghi rõ cả những việc bạn vốn dĩ muốn làm, những lời bạn vốn dĩ muốn nói, nhưng rốt cuộc đã không thực hiện được và những điều bạn đã nói hay lỡ làm mà bạn ước gì bạn đã không làm hay nói. Buổi sáng hôm sau, bạn hãy đọc to toàn bộ nội dung đó trước một tấm gương lớn và quan sát ngôn ngữ cơ thể bạn.\n' +
                '\n' + 'Hãy làm điều này thường xuyên và bạn sẽ nhìn thấy sự tự tin trong việc diễn đạt bản thân được cải thiện thấy rõ, về cuộc sống, những người có một số 1 thường cảm thấy thiếu một điều gì đó trong cuộc sống, mặc dù thoạt nhìn họ rất đủ đầy ở một số mặt.',
        },
        2: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.TWO + BIRTH_DATE_NUMBER_SUBSECTION.NINE,
            meaning: 'Người có hai số 1 (11) trong Biểu đồ ngày sinh là người may mắn nhất trong cả nhóm, bởi sự cân bằng trời cho trong việc diễn đạt nội tâm. Đây là một đặc điểm nên được sử dụng một cách khôn ngoan - không bao giờ lạm dụng nó cho mục đích thao túng người khác. (Đồng thời hãy nhớ đừng mất kiên nhẫn với những người không may mắn không có hai số 1 giống bạn, đặc biệt nếu đó là người yêu hoặc người bạn đời của bạn.) Người có hai số 1 thường có khả năng nhìn nhận các vấn đề hay các cuộc tranh luận theo cả hai mặt, và vì vậy họ hoàn toàn có khả năng chuyển sang hướng đối lập trong một cuộc thảo luận nếu quan điểm của bên đó có vẻ có giá trị hơn. Điều này giúp họ không bị sa vào tư duy bảo thủ, thứ khiến tầm hiểu biết bị giới hạn một chiều, và vì thế bản thân họ cũng thường ít khi bắt bẻ những “ lỗi sai ” của người khác. Có thể nói người có hai số 1 trong biểu đồ thường dễ có cuộc sống cân bằng, an vui, bất kể cuộc sống có diễn ra thế nào. Về nhận định này, tôi có hai điều muốn chia sẻ kỹ hơn : Một Biểu đồ ngày sinh sẽ bao gồm rất nhiều yếu tố chi tiết bên trong, yếu tố này hòa quyện với yếu tố kia, hay yếu tố này mâu thuẫn với yếu tố kia, làm giảm giá trị của yếu tố kia.\n' +
                '\n' + 'Ví dụ, nếu một người có được hai số 1 nhưng lại trống hoàn toàn cột giữa (4-5-6 - mang ý nghĩa Mũi tên uất giận, vì họ mãi không đạt được điều mình khát khao muốn có) , và đặc biệt nếu có thêm số 7 (hay 77, hay 777) thì người đó rất dễ gặp phải một trong những điều bất ý lớn trong các khía cạnh: sức khỏe, tiền tài, tình yêu, sự nghiệp ... Nhưng nhờ sức mạnh của hai số 1, người đó vẫn hay dùng lòng tin để tiếp thu cái mới, từ đó khiến bản thân gặp nhiều thiệt thòi. Tuy nhiên, nhờ trong Biểu đồ ngày sinh của tôi có hai số 1 (11) nên tôi có được một đặc điểm (như đã đề cập ở trên) : dễ dàng nhìn được hai mặt của một vấn đề, chịu thay đổi quan điểm một khi thấy các quan điểm khác cũng đúng hoặc có giá trị. Điều này đặc biệt ý nghĩa với các vấn đề mang tính trực giác, đòi hỏi sự hiểu biết sâu xa hơn những gì mắt thường nhìn thấy. Cho nên hiện giờ tôi đã thôi không còn dùng khái niệm “ thấy mới tin ” nữa, mà bắt đầu lắng tâm mình hơn, mỗi ngày một phát huy trực giác (còn gọi là “ con mắt ” bên trong) để cảm mọi việc, nhờ vậy tôi có thể tiếp thu nhiều cái mới mẻ hơn, rộng lớn hơn. Như vậy, hai số 1 (11) đã giúp tôi hóa giải bớt tính “ cứng đầu ” của Mũi tên 1-4-7 đó.\n' +
                '\n' + 'Trở lại với những đặc điểm nổi bật của hai số 1 (11) :\n' + '\n' + 'Chính nhờ những yếu tố tích cực, dung hòa và cân bằng này mà người có hai số 1 trong biểu đồ dễ trở thành các chính trị gia thành công hoặc người của công chúng, người nổi tiếng. Yếu tố hai số 1 làm nổi bật nhận thức về con người, cũng như cách biểu đạt bản thân và khả năng nhìn nhận vấn đề một cách đa chiều, không phiến diện, giúp giảm thiểu khả năng bị hiểu lầm.',
        },
        3: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.THREE + BIRTH_DATE_NUMBER_SUBSECTION.NINE,
            meaning: 'Với những người có ba số 1 trong Biểu đồ ngày sinh, có hai khả năng khá đối lập xảy ra trong thực tế. Khả năng thường gặp nhất là những người này thuộc dạng nói rất nhiều, thường có mặt trong rất nhiều cuộc trò chuyện sôi nổi mà trong đó họ trở nên nổi bật và thú vị. Nhìn chung họ thấy cuộc sống dễ chịu và thường cố gắng chia sẻ điều đó với những người xung quanh, Nhóm thứ hai là những người cũng có ba số 1 nhưng lại không có số nào ở Trục ngang Tinh thần (tức là không có các số 2-5-8) . Những người này khá im lặng, hướng nội, bẽn lẽn, đặc biệt là với người lạ. Tuy nhiên, họ có thể hoạt bát và nói nhiều khi trò chuyện với bạn bè thân thiết hoặc người thân trong nhà - đó là những lúc họ cảm thấy thoải mái. Những người này thường dễ diễn đạt cảm xúc hay nội tâm của mình bằng cách viết, vì khi đó dòng suy nghĩ của họ liền mạch hơn, không bị cản trở bởi sự nhạy cảm quá mức của họ. Nếu bạn thuộc nhóm này mà chưa biết sức mạnh khả năng viết lách của mình, hãy thử xem sao. Hãy xem viết lách là một cách để tập diễn đạt bản thân cho trôi chảy, khơi thông những cảm xúc rối rắm tắc nghẽn trong lòng, cũng như là một cách để tự chữa lành. Ngoài ra, còn một khả năng nữa ở những người có ba số 1 mà bản thân tôi quan sát thấy, đó là tâm trạng lúc vui lúc buồn. Tùy theo những yếu tố khác trong Biểu đồ ngày sinh mà tỷ lệ vui buồn sẽ gia giảm khác nhau, tốt nhất thì được 5/5, còn không thì 4/6, không nữa thì 3/7, lúc vui họ có xu hướng nói rất nhiều, lúc buồn thì ngồi im, không quan tâm tới ai.',
        },
        4: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.FOUR + BIRTH_DATE_NUMBER_SUBSECTION.NINE,
            meaning: 'Người có bốn số 1 trong ngày sinh thường gặp trục trặc với vấn đề diễn đạt bằng lời, và vì vậy, rất dễ bị người khác hiểu lầm. Nhưng cuộc sống nhanh chóng dạy họ giấu đi những cảm xúc rối rắm bằng một nụ cười, cho dù họ có khuynh hướng dẫn tiếp tục chịu đựng bên trong cho đến khi tự có ý thức giải tỏa những cảm xúc đó và sống lẹ làng hơn. Nói một cách dễ hiểu, những người có bốn số 1 thường tự làm mình khổ tâm. Số 1 mang đặc tính về “ cái tôi ” của mỗi người, vậy nên hãy tưởng tượng một người có đến bốn lần “ cái tôi ” như vậy sẽ như thế nào. Họ có “ cái tôi rất mạnh, nhưng rất khó diễn đạt những cảm giác sâu đậm như vậy về bản thân mình. Vì vậy, Thầy David khuyên: vì hạnh phúc của chính mình và của những người thân, những người có bốn số 1 phải học cách kiểm soát cảm xúc của mình. Khi họ thả lỏng hơn, bớt căng thẳng, bớt thiếu tự tin (đôi khi họ không nhận ra điều này, mà trái lại, họ có thể cảm thấy mình quá tự tin là đằng khác), họ sẽ cảm thấy ít bị cản trở hơn và diễn đạt cảm xúc của mình một cách thoải mái hơn, thay vì cứ đè nén những sầu muộn, rối rắm trong nội tâm của mình.',
        },
        5: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.FIVE + BIRTH_DATE_NUMBER_SUBSECTION.NINE,
            meaning: 'Với năm hay sáu số 1 trên Biểu đồ ngày sinh, “ cái tôi ” thường bị đè nén để giảm bớt các khó khăn trong việc diễn đạt cảm xúc cá nhân. Những người trẻ tuổi thuộc nhóm này thường cảm thấy buồn vì bị mọi người xung quanh hiểu lầm. Điều này dẫn đến sự tách rời, từ đó gây gia sự cô độc. Họ có thể phát triển theo hướng bị ám ảnh với ngoại hình và hành động của mình, cũng như thường gắn rất nhiều gương trong nhà nhưng lại có xu hướng giấu chúng đi để tránh người khác nghĩ họ quá tự tôn. Nhưng họ vẫn bí mật ngắm mình trong gương mỗi khi có dịp. Tính vị kỷ và “ tự lừa mình ” này có thể gây ra sự mất cân bằng về tâm thần, chúng ta có thể giúp trẻ thuộc nhóm có quá nhiều số 1 gia tăng nhận thức bằng cách cho chúng tham gia nhiều hoạt động nghệ thuật khác nhau, như viết lách, làm thơ, vẽ, làm đồ gốm,... Điều này có thể áp dụng được cho trẻ mọi lứa tuổi.'
        }
    },
    0: {
        1: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.ONE + BIRTH_DATE_NUMBER_SUBSECTION.ZERO,
            meaning: 'Những người có Biểu đồ ngày sinh có một số 1 thường gặp một chút khó khăn trong việc thể hiện bản thân qua ngôn ngữ. Điều này không có nghĩa là họ không thể nói chuyện một cách suôn sẻ, mà là họ khó diễn đạt được cảm xúc nội tâm của mình.\n' + '\n' + 'Họ có thể nói rất lưu loát và đầy thuyết phục về các đề tài không liên quan đến diễn đạt cảm xúc cá nhân, nhưng thường không biết cách biểu đạt bản thân hoặc diễn tả những gì mình đang cảm thấy. Chỉ khi nào họ học được cách làm chủ bản thân - kết quả của quá trình trưởng thành và thấu hiểu - thì điều này mới được cải thiện. Đôi khi họ sẽ cố ý nói ra những lời hoàn toàn trái ngược với suy nghĩ thật sự của mình như một kiểu phản ứng tự vệ - tức là họ Cố ý làm tổn thương hoặc xúc phạm người khác để tự bảo vệ bản thân mình. Điều này khiến vấn đề ban đầu trở nên nghiêm trọng hơn và gây ra những cuộc tranh cãi gay gắt. Họ cần tập suy nghĩ cẩn trọng trước khi phát biểu, và họ có thể làm được điều ấy bằng cách học kiểm soát phản ứng của bản thân trước các ý kiến, lời phê bình, vì những lời nói đã nói ra thì không thể thu hồi và cảm giác tổn thương rất khó được chữa lành. Để cải thiện hạn chế này, hãy lấy một quyển số trắng và ghi ngày tháng hiện tại. Sau đó, vào buổi tối, trước khi đi ngủ, hãy dành vài phút viết ra những suy nghĩ và cảm nhận của bạn về ngày hôm nay. Nhớ ghi rõ cả những việc bạn vốn dĩ muốn làm, những lời bạn vốn dĩ muốn nói, nhưng rốt cuộc đã không thực hiện được và những điều bạn đã nói hay lỡ làm mà bạn ước gì bạn đã không làm hay nói. Buổi sáng hôm sau, bạn hãy đọc to toàn bộ nội dung đó trước một tấm gương lớn và quan sát ngôn ngữ cơ thể bạn.\n' +
                '\n' + 'Hãy làm điều này thường xuyên và bạn sẽ nhìn thấy sự tự tin trong việc diễn đạt bản thân được cải thiện thấy rõ, về cuộc sống, những người có một số 1 thường cảm thấy thiếu một điều gì đó trong cuộc sống, mặc dù thoạt nhìn họ rất đủ đầy ở một số mặt.',
        },
        2: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.TWO + BIRTH_DATE_NUMBER_SUBSECTION.ZERO,
            meaning: 'Người có hai số 1 (11) trong Biểu đồ ngày sinh là người may mắn nhất trong cả nhóm, bởi sự cân bằng trời cho trong việc diễn đạt nội tâm. Đây là một đặc điểm nên được sử dụng một cách khôn ngoan - không bao giờ lạm dụng nó cho mục đích thao túng người khác. (Đồng thời hãy nhớ đừng mất kiên nhẫn với những người không may mắn không có hai số 1 giống bạn, đặc biệt nếu đó là người yêu hoặc người bạn đời của bạn.) Người có hai số 1 thường có khả năng nhìn nhận các vấn đề hay các cuộc tranh luận theo cả hai mặt, và vì vậy họ hoàn toàn có khả năng chuyển sang hướng đối lập trong một cuộc thảo luận nếu quan điểm của bên đó có vẻ có giá trị hơn. Điều này giúp họ không bị sa vào tư duy bảo thủ, thứ khiến tầm hiểu biết bị giới hạn một chiều, và vì thế bản thân họ cũng thường ít khi bắt bẻ những “ lỗi sai ” của người khác. Có thể nói người có hai số 1 trong biểu đồ thường dễ có cuộc sống cân bằng, an vui, bất kể cuộc sống có diễn ra thế nào. Về nhận định này, tôi có hai điều muốn chia sẻ kỹ hơn : Một Biểu đồ ngày sinh sẽ bao gồm rất nhiều yếu tố chi tiết bên trong, yếu tố này hòa quyện với yếu tố kia, hay yếu tố này mâu thuẫn với yếu tố kia, làm giảm giá trị của yếu tố kia.\n' +
                '\n' + 'Ví dụ, nếu một người có được hai số 1 nhưng lại trống hoàn toàn cột giữa (4-5-6 - mang ý nghĩa Mũi tên uất giận, vì họ mãi không đạt được điều mình khát khao muốn có) , và đặc biệt nếu có thêm số 7 (hay 77, hay 777) thì người đó rất dễ gặp phải một trong những điều bất ý lớn trong các khía cạnh: sức khỏe, tiền tài, tình yêu, sự nghiệp ... Nhưng nhờ sức mạnh của hai số 1, người đó vẫn hay dùng lòng tin để tiếp thu cái mới, từ đó khiến bản thân gặp nhiều thiệt thòi. Tuy nhiên, nhờ trong Biểu đồ ngày sinh của tôi có hai số 1 (11) nên tôi có được một đặc điểm (như đã đề cập ở trên) : dễ dàng nhìn được hai mặt của một vấn đề, chịu thay đổi quan điểm một khi thấy các quan điểm khác cũng đúng hoặc có giá trị. Điều này đặc biệt ý nghĩa với các vấn đề mang tính trực giác, đòi hỏi sự hiểu biết sâu xa hơn những gì mắt thường nhìn thấy. Cho nên hiện giờ tôi đã thôi không còn dùng khái niệm “ thấy mới tin ” nữa, mà bắt đầu lắng tâm mình hơn, mỗi ngày một phát huy trực giác (còn gọi là “ con mắt ” bên trong) để cảm mọi việc, nhờ vậy tôi có thể tiếp thu nhiều cái mới mẻ hơn, rộng lớn hơn. Như vậy, hai số 1 (11) đã giúp tôi hóa giải bớt tính “ cứng đầu ” của Mũi tên 1-4-7 đó.\n' +
                '\n' + 'Trở lại với những đặc điểm nổi bật của hai số 1 (11) :\n' + '\n' + 'Chính nhờ những yếu tố tích cực, dung hòa và cân bằng này mà người có hai số 1 trong biểu đồ dễ trở thành các chính trị gia thành công hoặc người của công chúng, người nổi tiếng. Yếu tố hai số 1 làm nổi bật nhận thức về con người, cũng như cách biểu đạt bản thân và khả năng nhìn nhận vấn đề một cách đa chiều, không phiến diện, giúp giảm thiểu khả năng bị hiểu lầm.',
        },
        3: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.THREE + BIRTH_DATE_NUMBER_SUBSECTION.ZERO,
            meaning: 'Với những người có ba số 1 trong Biểu đồ ngày sinh, có hai khả năng khá đối lập xảy ra trong thực tế. Khả năng thường gặp nhất là những người này thuộc dạng nói rất nhiều, thường có mặt trong rất nhiều cuộc trò chuyện sôi nổi mà trong đó họ trở nên nổi bật và thú vị. Nhìn chung họ thấy cuộc sống dễ chịu và thường cố gắng chia sẻ điều đó với những người xung quanh, Nhóm thứ hai là những người cũng có ba số 1 nhưng lại không có số nào ở Trục ngang Tinh thần (tức là không có các số 2-5-8) . Những người này khá im lặng, hướng nội, bẽn lẽn, đặc biệt là với người lạ. Tuy nhiên, họ có thể hoạt bát và nói nhiều khi trò chuyện với bạn bè thân thiết hoặc người thân trong nhà - đó là những lúc họ cảm thấy thoải mái. Những người này thường dễ diễn đạt cảm xúc hay nội tâm của mình bằng cách viết, vì khi đó dòng suy nghĩ của họ liền mạch hơn, không bị cản trở bởi sự nhạy cảm quá mức của họ. Nếu bạn thuộc nhóm này mà chưa biết sức mạnh khả năng viết lách của mình, hãy thử xem sao. Hãy xem viết lách là một cách để tập diễn đạt bản thân cho trôi chảy, khơi thông những cảm xúc rối rắm tắc nghẽn trong lòng, cũng như là một cách để tự chữa lành. Ngoài ra, còn một khả năng nữa ở những người có ba số 1 mà bản thân tôi quan sát thấy, đó là tâm trạng lúc vui lúc buồn. Tùy theo những yếu tố khác trong Biểu đồ ngày sinh mà tỷ lệ vui buồn sẽ gia giảm khác nhau, tốt nhất thì được 5/5, còn không thì 4/6, không nữa thì 3/7, lúc vui họ có xu hướng nói rất nhiều, lúc buồn thì ngồi im, không quan tâm tới ai.',
        },
        4: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.FOUR + BIRTH_DATE_NUMBER_SUBSECTION.ZERO,
            meaning: 'Người có bốn số 1 trong ngày sinh thường gặp trục trặc với vấn đề diễn đạt bằng lời, và vì vậy, rất dễ bị người khác hiểu lầm. Nhưng cuộc sống nhanh chóng dạy họ giấu đi những cảm xúc rối rắm bằng một nụ cười, cho dù họ có khuynh hướng dẫn tiếp tục chịu đựng bên trong cho đến khi tự có ý thức giải tỏa những cảm xúc đó và sống lẹ làng hơn. Nói một cách dễ hiểu, những người có bốn số 1 thường tự làm mình khổ tâm. Số 1 mang đặc tính về “ cái tôi ” của mỗi người, vậy nên hãy tưởng tượng một người có đến bốn lần “ cái tôi ” như vậy sẽ như thế nào. Họ có “ cái tôi rất mạnh, nhưng rất khó diễn đạt những cảm giác sâu đậm như vậy về bản thân mình. Vì vậy, Thầy David khuyên: vì hạnh phúc của chính mình và của những người thân, những người có bốn số 1 phải học cách kiểm soát cảm xúc của mình. Khi họ thả lỏng hơn, bớt căng thẳng, bớt thiếu tự tin (đôi khi họ không nhận ra điều này, mà trái lại, họ có thể cảm thấy mình quá tự tin là đằng khác), họ sẽ cảm thấy ít bị cản trở hơn và diễn đạt cảm xúc của mình một cách thoải mái hơn, thay vì cứ đè nén những sầu muộn, rối rắm trong nội tâm của mình.',
        },
        5: {
            title: BIRTH_DATE_NUMBER_VNM_SUBSECTION.FIVE + BIRTH_DATE_NUMBER_SUBSECTION.ZERO,
            meaning: 'Với năm hay sáu số 1 trên Biểu đồ ngày sinh, “ cái tôi ” thường bị đè nén để giảm bớt các khó khăn trong việc diễn đạt cảm xúc cá nhân. Những người trẻ tuổi thuộc nhóm này thường cảm thấy buồn vì bị mọi người xung quanh hiểu lầm. Điều này dẫn đến sự tách rời, từ đó gây gia sự cô độc. Họ có thể phát triển theo hướng bị ám ảnh với ngoại hình và hành động của mình, cũng như thường gắn rất nhiều gương trong nhà nhưng lại có xu hướng giấu chúng đi để tránh người khác nghĩ họ quá tự tôn. Nhưng họ vẫn bí mật ngắm mình trong gương mỗi khi có dịp. Tính vị kỷ và “ tự lừa mình ” này có thể gây ra sự mất cân bằng về tâm thần, chúng ta có thể giúp trẻ thuộc nhóm có quá nhiều số 1 gia tăng nhận thức bằng cách cho chúng tham gia nhiều hoạt động nghệ thuật khác nhau, như viết lách, làm thơ, vẽ, làm đồ gốm,... Điều này có thể áp dụng được cho trẻ mọi lứa tuổi.'
        }
    },
}

