import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HomePage from '../component/HomePage'

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Numerology</title>
                <meta name="description" content="Generated by create next app"/>
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
                      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
                      crossOrigin="anonymous"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <HomePage/>
        </div>
    )
}

export default Home
